import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendEmailVerification, sendPasswordResetEmail, reload, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, doc, collection, getDoc, getDocs, setDoc, deleteDoc, writeBatch, serverTimestamp, deleteField } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const firebaseConfig = {
  apiKey: 'AIzaSyBWQTbyCFJxLsypcyVIK5gC4-KeXnxXfEw',
  authDomain: 'past-paper-tracker-51a18.firebaseapp.com',
  projectId: 'past-paper-tracker-51a18',
  storageBucket: 'past-paper-tracker-51a18.firebasestorage.app',
  messagingSenderId: '7364242011',
  appId: '1:7364242011:web:839ff4cc39b155d3aeed7e'
};
const TEACHER_UID = 'yObDW0xHlmYFqgEcZT2xjKgVwxn1';
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const state = { user:null, teacher:false, profile:null, memberId:null, invite:readInvite(), inviteUrl:location.hash?location.href:'', invitePreview:null, tab:'today', authMode:'signin', busy:false, notice:'', error:'', branding:{title:'Past Paper Tracker', subtitle:'Your practice space'}, classes:[], students:[], assignments:[], submissions:[], selectedStudent:'', membershipStudent:'', editingEntryId:null, editingStudent:'', deletingStudent:'', editingAssignment:'', deletingAssignment:'', reportType:'student', reportStudent:'', reportClass:'', reportFrom:'2019-01-01', reportTo:'', showAddStudent:false, showAddClass:false, paper:'all', progressClass:'all', markView:'percent', selectedPoint:null, selectedClass:'', selectedExam:'', showExplained:false, questionStatus:{}, examTotals:{}, importData:null, scheduleRows:[], scheduleClass:'', scheduleDate:'', freeClass:'', freeYear:new Date().getFullYear(), freeSession:'jun', freePaper:'', freeVariant:'1', detail:null };
const esc = v => String(v ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const today = () => { const p = Object.fromEntries(new Intl.DateTimeFormat('en', {timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value])); return `${p.year}-${p.month}-${p.day}`; };
state.scheduleDate=today();
const emailKey = v => String(v ?? '').trim().toLowerCase();
const btn = (label,action,extra='',kind='') => `<button type="button" class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
const card = (title,body,extra='') => `<section class="card"><div class="row" style="justify-content:space-between;margin-bottom:14px"><h2 style="margin:0">${title}</h2>${extra}</div>${body}</section>`;
const dateLabel = v => v ? new Date(v+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}) : '—';
const className = id => state.classes.find(c=>c.id===id)?.name || id;
const nameFor = id => state.students.find(s=>s.id===id)?.name || id;
const me = () => state.memberId;
const LEVELS={olevel:{name:'O Level',papers:[2,4,6],totals:{2:40,4:80,6:40}},as:{name:'AS Level',papers:[1,2],totals:{1:40,2:60}},a2:{name:'A2 Level',papers:[4],totals:{4:100}},combined:{name:'Combined Science',papers:[2,4,6],totals:{}},preig:{name:'Pre-IG',papers:[1,3,6],totals:{1:40,3:80,6:40}}};
const SESSIONS={mar:'March',jun:'May/June',nov:'Oct/Nov'};
const levelOf=id=>state.classes.find(c=>c.id===id)?.level||'';
const levelName=id=>LEVELS[id]?.name||'Choose level';
const examKey=(level,paper,year,session,variant)=>`${level}-${paper}-${year}-${session}-${variant}`;
const examTitle=(level,paper,year,session,variant)=>`${levelName(level)} · Paper ${paper}${variant} · ${SESSIONS[session]} ${year}`;
const examTotalKey=(classId,key)=>`${classId}_${key}`;
const fixedTotal=(level,paper,year)=>Number(year)>=2023&&level!=='combined'?LEVELS[level]?.totals?.[Number(paper)]||null:null;
const totalFor=(classId,key,level,paper,year)=>level==='combined'?null:fixedTotal(level,paper,year)||Number(state.examTotals[examTotalKey(classId,key)]?.total)||null;
const variants=session=>session==='mar'?[2]:[1,2,3];
const years=()=>Array.from({length:new Date().getFullYear()-2018},(_,i)=>new Date().getFullYear()-i);
const opt=(value,label,selected)=>`<option value="${esc(value)}" ${String(value)===String(selected)?'selected':''}>${esc(label)}</option>`;
const levelOptions=selected=>Object.entries(LEVELS).map(([id,x])=>opt(id,x.name,selected)).join('');
function classFor(s){if(s.classId&&state.classes.some(c=>c.id===s.classId))return s.classId;const student=state.students.find(x=>x.id===s.studentId)||state.profile;const ids=(student?.classIds||[]).filter(id=>state.classes.some(c=>c.id===id));const matches=ids.filter(id=>{const level=levelOf(id);return level===s.subject||(s.subject==='alevel'&&(level==='as'&&[1,2].includes(Number(s.paper))||level==='a2'&&Number(s.paper)===4));});return matches.length===1?matches[0]:ids.length===1?ids[0]:'';}
function resultFor(a,studentId=me()){return state.submissions.find(s=>s.studentId===studentId&&s.classId===a.classId&&s.assignmentId===a.id)||state.submissions.find(s=>s.studentId===studentId&&classFor(s)===a.classId&&s.examKey===a.examKey);}
function parseQuestions(raw){const parts=String(raw||'').split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);if(parts.length>30)throw new Error('Please list no more than 30 questions.');const normalized=parts.map(x=>x.replace(/[\s().]/g,'').toLowerCase());const invalid=parts.filter((_,i)=>!/^\d{1,2}[a-z]?(?:iv|iii|ii|i|v)?$/.test(normalized[i]));if(invalid.length)throw new Error(`Write each full question, such as 2bi,2bii. Check: ${invalid.join(', ')}`);return [...new Set(normalized)];}
function questionBits(raw){const code=String(raw).replace(/[\s().]/g,'').toLowerCase(),m=code.match(/^(\d{1,2})([a-z]?)(iv|iii|ii|i|v)?$/);return m?{code,group:`${m[1]}${m[2]}`,part:m[3]||'',label:`Q${m[1]}${m[2]?`(${m[2]})`:''}`}:{code,group:code,part:'',label:`Q${code}`};}
function readInvite(){const raw=new URLSearchParams(location.hash.slice(1)).get('invite');if(!raw)return null;const split=raw.indexOf('.');return split>0?{studentId:raw.slice(0,split),code:raw.slice(split+1)}:null;}
function newCode(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
function inviteLink(s){return `${location.origin}${location.pathname}#invite=${encodeURIComponent(s.id+'.'+s.inviteCode)}`;}
const published = a => a.dueDate <= today();
const isoDate = v => v?.toDate ? v.toDate().toISOString() : String(v||'');
const sortDate = (a,b) => isoDate(a.submittedAt||a.date).localeCompare(isoDate(b.submittedAt||b.date));

function enrichSubmissions(){state.submissions=state.submissions.map(s=>{const a=state.assignments.find(x=>x.id===s.assignmentId&&x.classId===s.classId);return a?{...a,...s,total:Number(s.total)||Number(a.total)||0,examLabel:assignmentTitle(a),examKey:a.examKey,paper:Number(a.paper),year:Number(a.year),session:a.session,variant:Number(a.variant),subject:a.subject}:s;});}
function friendlyError(e){
  const code=e?.code||'';
  if(['auth/invalid-credential','auth/wrong-password','auth/user-not-found'].includes(code)) return 'Email or password was not accepted.';
  if(code==='auth/email-already-in-use') return 'This email already has an account. Choose Sign in instead.';
  if(code==='auth/weak-password') return 'Choose a stronger password with at least 6 characters.';
  if(code==='permission-denied') return 'Firebase denied access. Check that your email is verified and that you opened your own invitation link. If it still fails, ask your teacher to check the published rules.';
  return e?.message || 'Something went wrong. Please try again.';
}
function message(text,bad=false){state.notice=bad?'':text;state.error=bad?text:'';render();}
async function run(task){ if(state.busy)return;state.busy=true;state.error='';render();try{await task();}catch(e){console.error(e);state.error=friendlyError(e);}finally{state.busy=false;render();} }
async function ensureVerifiedToken(){
  const user=auth.currentUser;
  if(!user)throw new Error('Sign in before connecting your invitation.');
  await reload(user);
  state.user=auth.currentUser;
  if(!state.user.emailVerified)throw new Error('Open the verification email first, then return here.');
  const token=await state.user.getIdTokenResult(true);
  if(token.claims.email_verified!==true)throw new Error('Firebase has not updated your verification yet. Please wait a moment and try again.');
}
async function readCollection(ref){const snap=await getDocs(ref);return snap.docs.map(d=>({id:d.id,...d.data()}));}

async function refresh(){
  const settings=await getDoc(doc(db,'settings','app'));
  state.branding=settings.exists()?{title:settings.data().title||'Past Paper Tracker',subtitle:settings.data().subtitle||''}:state.branding;
  if(state.teacher){
    state.classes=await readCollection(collection(db,'classes'));
    state.students=await readCollection(collection(db,'students'));
  }else{
    const member=await getDoc(doc(db,'members',state.user.uid));
    if(!member.exists()){state.profile=null;state.memberId=null;state.classes=[];state.assignments=[];state.submissions=[];return;}
    state.memberId=member.data().studentId;
    const profile=await getDoc(doc(db,'students',state.memberId));
    if(!profile.exists())throw new Error('Your student record could not be found. Please ask your teacher.');
    state.profile={id:state.memberId,...profile.data()};
    state.classes=(await Promise.all((state.profile.classIds||[]).map(async id=>{const x=await getDoc(doc(db,'classes',id));return x.exists()?{id,...x.data()}:null;}))).filter(Boolean);
    state.students=[state.profile];
  }
  state.assignments=(await Promise.all(state.classes.map(c=>readCollection(collection(db,'classes',c.id,'assignments')).then(a=>a.map(x=>({...x,classId:c.id})))))).flat();
  state.submissions=state.teacher?(await Promise.all(state.students.map(s=>readCollection(collection(db,'students',s.id,'submissions')).then(a=>a.map(x=>({...x,studentId:s.id})))))).flat():(await readCollection(collection(db,'students',state.memberId,'submissions'))).map(x=>({...x,studentId:state.memberId}));
  state.questionStatus=Object.fromEntries((await readCollection(collection(db,'questionStatus'))).map(x=>[x.key,x.explained]));
  state.examTotals=Object.fromEntries((await readCollection(collection(db,'examTotals'))).map(x=>[x.id,x]));
  enrichSubmissions();
  if(!state.selectedClass||!state.classes.some(c=>c.id===state.selectedClass))state.selectedClass=state.classes[0]?.id||'';
  if(!state.scheduleClass||!state.classes.some(c=>c.id===state.scheduleClass))state.scheduleClass=state.classes[0]?.id||'';
  if(!state.freeClass||!state.classes.some(c=>c.id===state.freeClass))state.freeClass=state.classes[0]?.id||'';
  if(!state.selectedStudent||!state.students.some(s=>s.id===state.selectedStudent))state.selectedStudent=state.students[0]?.id||'';
  if(!state.reportStudent||!state.students.some(s=>s.id===state.reportStudent))state.reportStudent=state.students[0]?.id||'';
  if(!state.reportClass||!state.classes.some(c=>c.id===state.reportClass))state.reportClass=state.classes[0]?.id||'';
}
function top(){return `<div class="shell"><header class="top"><div class="brand">${esc(state.branding.title)}<small>${esc(state.branding.subtitle)}</small></div><div class="top-actions"><span class="small muted">${state.teacher?'Teacher':esc(state.profile?.name||'Student')}</span>${btn('Sign out','signout','','ghost')}</div></header>`;}
function tabs(){const options=state.teacher?[['today','Overview'],['schedule','Schedule'],['questions','Classroom questions'],['progress','Progress'],['reports','Reports'],['roster','Classes'],['settings','Settings']]:[['today','My assignments'],['history','My submissions'],['questions','My questions'],['progress','My progress']];return `<nav class="tabs" aria-label="Dashboard sections">${options.map(([id,label])=>`<button data-action="tab" data-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('')}</nav>`;}
function authScreen(){return `<main class="auth-wrap"><section class="auth-card"><div class="eyebrow">${esc(state.branding.title)}</div><h1>${state.authMode==='signup'?'Create your account':state.authMode==='reset'?'Reset your password':'Welcome back'}</h1><p class="muted">${state.authMode==='signup'?'Use your own email and the private invitation your teacher gave you. Verify your email before viewing results.':state.authMode==='reset'?'We will email you a password reset link.':'Sign in to see your own work and progress.'}</p><form id="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required></label>${state.authMode!=='reset'?`<label>Password<input name="password" type="password" minlength="6" autocomplete="${state.authMode==='signup'?'new-password':'current-password'}" required></label>`:''}<button class="btn" type="submit" ${state.busy?'disabled':''}>${state.authMode==='signup'?'Create account':state.authMode==='reset'?'Send reset link':'Sign in'}</button></form><div class="auth-links">${state.authMode!=='signin'?btn('Sign in','auth-mode','data-mode="signin"','ghost'):''}${state.authMode!=='signup'?btn('Create account','auth-mode','data-mode="signup"','ghost'):''}${state.authMode!=='reset'?btn('Forgot password?','auth-mode','data-mode="reset"','ghost'):''}</div>${state.notice?`<div class="notice" role="status">${esc(state.notice)}</div>`:''}${state.error?`<div class="notice error" role="alert">${esc(state.error)}</div>`:''}</section></main>`;}
function verifyScreen(){return `<main class="auth-wrap"><section class="auth-card"><div class="eyebrow">One quick check</div><h1>Verify your email</h1><p class="muted">Firebase has sent a verification link to ${esc(state.user.email)}. Open that email, click the link, then return here.</p>${btn('I verified my email','check-verification')} ${btn('Send another email','resend-verification','','secondary')} ${btn('Sign out','signout','','ghost')}${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}</section></main>`;}
function claimScreen(){return `<main class="auth-wrap"><section class="auth-card"><div class="eyebrow">Connect your earlier work</div><h1>Use your invitation</h1><p class="muted">Your teacher’s private link connects this email to your existing marks and questions. Open that link, or paste it below.</p><form id="claim-form"><label>Private invitation link<input name="invite" required placeholder="Paste the link your teacher gave you" value="${esc(state.inviteUrl)}"></label><button class="btn" type="submit">Connect my dashboard</button></form><div class="auth-links">${btn('Sign out','signout','','ghost')}</div>${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}</section></main>`;}
function stat(label,value,note=''){return `<div class="stat"><div class="small muted">${label}</div><strong>${value}</strong><div class="small muted">${note}</div></div>`;}

function assignmentTitle(a){return a.examLabel||examTitle(a.subject||levelOf(a.classId),a.paper,a.year,a.session,a.variant);}

function studentToday(){
 const sorted=state.assignments.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
 const row=a=>{const s=resultFor(a),total=totalFor(a.classId,a.examKey,a.subject||levelOf(a.classId),a.paper,a.year);return `<div class="item"><div><div class="eyebrow">${esc(className(a.classId))} · ${dateLabel(a.dueDate)}</div><h3>${esc(assignmentTitle(a))}</h3><p class="small muted">${total?`${total} marks`:'Enter your total marks'} · Paper ${esc(a.paper)}</p></div><div class="actions"><span class="pill ${s?'':'wait'}">${s?'Submitted':a.dueDate>today()?'Upcoming':'Due'}</span>${btn(s?'View result':'Submit result','result',`data-id="${esc(a.id)}"`,'secondary')}</div></div>`;};
 return `<div class="stats">${stat('Assigned',sorted.length)}${stat('Submitted',sorted.filter(a=>resultFor(a)).length)}${stat('Coming up',sorted.filter(a=>a.dueDate>today()).length)}</div><div class="stack">${card('Your assigned exams',sorted.map(row).join('')||'<div class="empty">Nothing assigned yet.</div>')}${card('Submit an exam',btn('Submit an exam','free-result'))}</div>`;
}
function resultForm(id){
 const a=state.assignments.find(x=>x.id===id),old=state.submissions.find(x=>x.id===id&&x.studentId===me()),s=a?resultFor(a):old;
 const free=!a;
 const classId=a?.classId||s?.classId||classFor(s||{})||state.freeClass,level=levelOf(classId);
 const year=free?Number(s?.year||state.freeYear):Number(a.year),session=free?(s?.session||state.freeSession):a.session,paper=free?Number(s?.paper||state.freePaper||LEVELS[level]?.papers[0]):Number(a.paper),variant=free?Number(s?.variant||state.freeVariant):Number(a.variant);
 const key=a?.examKey||s?.examKey||examKey(level,paper,year,session,variant);
 const total=totalFor(classId,key,level,paper,year),hasClass=state.classes.some(c=>c.id===classId&&LEVELS[c.level]);
 const examFields=free&&!s?`<div class="fields"><label>Class<select name="classId" data-free="class">${state.classes.filter(c=>LEVELS[c.level]).map(c=>opt(c.id,`${c.name} · ${levelName(c.level)}`,classId)).join('')}</select></label><label>Year<select name="year" data-free="year">${years().map(y=>opt(y,y,year)).join('')}</select></label><label>Session<select name="session" data-free="session">${Object.entries(SESSIONS).map(([x,y])=>opt(x,y,session)).join('')}</select></label><label>Paper<select name="paper" data-free="paper">${(LEVELS[level]?.papers||[]).map(p=>opt(p,`Paper ${p}`,paper)).join('')}</select></label><label>Variant<select name="variant" data-free="variant">${variants(session).map(v=>opt(v,`Variant ${v}`,session==='mar'?2:variant)).join('')}</select></label></div>`:free?`<h3>${esc(s.examLabel||examTitle(level,paper,year,session,variant))}</h3>`:'';
 const form=hasClass?`<form id="result-form" data-id="${esc(s?.id||id||'')}" data-assignment="${esc(a?.id||'')}">${examFields}<div class="fields"><label>Mark<input name="score" type="number" min="0" max="300" step="1" required value="${esc(s?.score??'')}"></label><label>Total marks<input name="total" type="number" min="1" max="300" step="1" ${total?'readonly':''} required value="${esc(total||s?.total||'')}"></label><label>Time taken (minutes)<input name="minutes" type="number" min="1" max="1440" step="1" required value="${esc(s?.minutes??'')}"></label><label class="wide">Questions I still need help with<textarea name="questions" rows="3" placeholder="2bi,2bii,4c">${esc((s?.questions||[]).join(','))}</textarea></label></div><p class="helper">Write the full question each time: 2bi,2bii,2biii, not 2bi,ii,iii. For example: 2bi,2bii,4c,4bii,4a,5c.</p><div class="form-actions"><button class="btn" type="submit">${s?'Save changes':'Save result'}</button>${btn('Cancel','close-detail','','secondary')}</div></form>`:'<p class="empty">Your class needs a level before exams can be submitted. Ask your teacher to set it.</p>';
 return card(free?(s?'Edit submission':'Submit an exam'):(s?'Edit result':'Submit result'),`<div class="eyebrow">${esc(className(classId))}${a?` · Due ${dateLabel(a.dueDate)}`:''}</div>${a?`<h3>${esc(assignmentTitle(a))}</h3>`:''}${form}`);
}
function receipt(id){const a=state.assignments.find(x=>x.id===id),s=a?resultFor(a):state.submissions.find(x=>x.id===id&&x.studentId===me());if(!s)return card('Submission','<div class="empty">Result not found.</div>');return card('Your submission',`<h3>${esc(s.examLabel||assignmentTitle(a||s))}</h3><div class="receipt"><p><strong>${s.score}/${s.total}</strong> marks (${percentage(s)}%)</p><p>${s.minutes} minutes</p><p>Questions: ${s.questions?.length?esc(s.questions.join(', ')):'None'}</p><p class="small muted">Saved ${esc(isoDate(s.submittedAt).slice(0,16).replace('T',' '))}</p></div><div class="form-actions">${btn('Edit','result',`data-id="${esc(s.id)}"`,'secondary')}${btn('Delete','ask-delete',`data-id="${esc(s.id)}"`,'danger')}${btn('Back','close-detail','','ghost')}</div>`);}
function studentHistory(){const rows=state.submissions.slice().sort((a,b)=>-sortDate(a,b)).map(s=>`<div class="item"><div><div class="eyebrow">${esc(className(classFor(s)))}</div><h3>${esc(s.examLabel||assignmentTitle(s))}</h3><p class="small muted">${s.score}/${s.total} marks · ${percentage(s)}% · ${s.minutes} min · ${dateLabel(isoDate(s.submittedAt).slice(0,10))}</p><p class="small muted">Questions: ${s.questions?.length?esc(s.questions.join(', ')):'None'}</p></div><div class="actions">${btn('View','receipt',`data-id="${esc(s.id)}"`,'secondary')}${btn('Edit','result',`data-id="${esc(s.id)}"`,'secondary')}${btn('Delete','ask-delete',`data-id="${esc(s.id)}"`,'danger')}</div></div>`).join('');return card('My submissions',rows||'<div class="empty">Your results will appear here.</div>');}

function questionGroups(records){
 const groups=new Map();
 for(const s of records){const classId=classFor(s),key=s.examKey||s.examLabel||s.assignmentId;if(!classId||!key)continue;for(const raw of s.questions||[]){if(!String(raw).trim())continue;const q=questionBits(raw),id=`${classId}|${key}|${q.group}`;if(!groups.has(id))groups.set(id,{id,classId,examKey:key,exam:s.examLabel||assignmentTitle(s),label:q.label,parts:new Map(),students:new Set(),raw:[]});const group=groups.get(id);group.students.add(s.studentId);const part=group.parts.get(q.part)||new Set();part.add(s.studentId);group.parts.set(q.part,part);group.raw.push({code:q.code,studentId:s.studentId});}}
 return [...groups.values()].sort((a,b)=>a.exam.localeCompare(b.exam)||a.label.localeCompare(b.label,undefined,{numeric:true}));
}

function questionPanel(teacher){
 const records=teacher?state.submissions.filter(s=>classFor(s)===state.selectedClass):state.submissions;
 const all=questionGroups(records),classId=state.selectedClass;
 const exams=[...new Map(records.filter(s=>s.examKey).map(s=>[s.examKey,s.examLabel||assignmentTitle(s)])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
 const selected=exams.some(([key])=>key===state.selectedExam)?state.selectedExam:exams[0]?.[0]||'';
 const examStatus=state.questionStatus[`exam|${classId}|${selected}`];
 const shown=all.filter(g=>!teacher||g.examKey===selected&&(state.showExplained?(state.questionStatus[g.id]||examStatus):(!state.questionStatus[g.id]&&!examStatus)));
 const selectedResults=records.filter(s=>s.examKey===selected),sample=selectedResults[0],isVariable=sample&&Number(sample.year)<2023&&sample.subject!=='combined';
 const counts=new Map();for(const x of selectedResults)counts.set(Number(x.total),(counts.get(Number(x.total))||0)+1);
 const popular=[...counts].sort((a,b)=>b[1]-a[1]||a[0]-b[0]);
 const totalCard=teacher&&isVariable?`<div class="total-tool"><strong>Total marks for this exam</strong><p class="small muted">Student totals: ${esc(popular.map(([total,count])=>`${total} (${count})`).join(', ')||'None yet')}. Students can edit their total until you lock it.</p><div class="row"><input id="lock-total" aria-label="Final total marks" type="number" min="1" max="300" value="${esc(state.examTotals[examTotalKey(classId,selected)]?.total||popular[0]?.[0]||'')}" style="max-width:140px">${btn('Lock total','lock-total',`data-class="${esc(classId)}" data-exam="${esc(selected)}"`,'secondary')}</div></div>`:'';
 const filters=teacher?`<div class="filters"><label>Class<select data-change="selectedClass">${state.classes.map(c=>opt(c.id,c.name,classId)).join('')}</select></label><label>Exam<select data-change="selectedExam">${exams.map(([key,name])=>opt(key,name,selected)).join('')}</select></label></div>${totalCard}<div class="form-actions">${btn(state.showExplained?'Show questions to explain':'Show explained','show-explained','','secondary')}${selected?btn(examStatus?'Reopen this exam':'Finish explaining this exam','finish-exam',`data-class="${esc(classId)}" data-exam="${esc(selected)}"`,'secondary'):''}</div>`:'';
 const body=shown.map(g=>{const parts=[...g.parts.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}));const summary=parts.map(([part,names])=>`${part||'Whole part'} · ${names.size}`).join('   •   ');return `<div class="question-tile"><div class="row" style="justify-content:space-between"><div><div class="eyebrow">${esc(g.exam)}${teacher?'':` · ${esc(className(g.classId))}`}</div><strong>${esc(g.label)}</strong></div><span class="pill ${state.questionStatus[g.id]?'':'wait'}">${g.students.size} student${g.students.size===1?'':'s'}</span></div><p class="part-summary">${esc(summary)}</p><details><summary>See who asked and which parts</summary>${parts.map(([part,ids])=>`<p class="small">${esc(part||'Whole part')}: ${esc([...ids].map(nameFor).join(', '))}</p>`).join('')}</details>${teacher?`<div class="form-actions">${btn(state.questionStatus[g.id]?'Return to list':'Mark explained','toggle-question',`data-key="${esc(g.id)}"`,'secondary')}</div>`:''}</div>`;}).join('')||'<div class="empty">No questions here yet.</div>';
 return card(teacher?'Questions to explain':'Questions I asked',filters+body);
}
function percentage(s){return Number((100 * s.score / s.total).toFixed(1));}
function chart(rows,key,label){
  if(!rows.length)return '<div class="empty">No results yet.</div>';
  const values=rows.map(s=>key==='percent'?percentage(s):key==='marks'?Number(s.score):Number(s.minutes));
  const max=key==='percent'?100:key==='marks'?Math.max(1,...rows.map(s=>Number(s.total)||0)):Math.max(60,Math.ceil(Math.max(...values)/20)*20);
  const w=500,h=220,l=42,r=16,t=20,b=35,x=i=>l+(w-l-r)*i/Math.max(1,values.length-1),y=v=>h-b-(h-t-b)*v/max;
  const color=key==='minutes'?'#6196de':'#1d5fba';
  const points=rows.map((s,i)=>{
    const exact=`${s.score}/${s.total} marks (${percentage(s)}%) · ${s.minutes} min`;
    const description=`${s.examLabel||'Exam'}: ${exact}`;
    const active=state.selectedPoint?.id===s.id&&state.selectedPoint?.key===key;
    return `<g class="plot-point ${active?'selected':''}" data-action="inspect-point" data-id="${esc(s.id)}" data-key="${key}" role="button" tabindex="0" aria-label="${esc(description)}"><circle cx="${x(i)}" cy="${y(values[i])}" r="15" class="point-hit"/><circle cx="${x(i)}" cy="${y(values[i])}" r="5" fill="${color}"/></g>`;
  }).join('');
  return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="group" aria-label="${esc(label)}. Tap a point for its exact result."><line class="gridline" x1="${l}" y1="${y(0)}" x2="${w-r}" y2="${y(0)}"/><line class="gridline" x1="${l}" y1="${y(max/2)}" x2="${w-r}" y2="${y(max/2)}"/><line class="gridline" x1="${l}" y1="${y(max)}" x2="${w-r}" y2="${y(max)}"/><text x="2" y="${y(0)+4}">0</text><text x="2" y="${y(max/2)+4}">${max/2}</text><text x="2" y="${y(max)+4}">${max}</text><path d="M${values.map((v,i)=>`${x(i)},${y(v)}`).join(' L')}" fill="none" stroke="${color}" stroke-width="3"/>${points}<text x="${l}" y="${h-6}">${esc(isoDate(rows[0].submittedAt).slice(0,10))}</text><text x="${w-r}" y="${h-6}" text-anchor="end">${esc(isoDate(rows.at(-1).submittedAt).slice(0,10))}</text></svg>`;
}
function pointDetails(rows,key){
  const selected=state.selectedPoint?.key===key&&rows.find(s=>s.id===state.selectedPoint.id);
  if(!selected)return '<p class="helper">Tap a point to see the exam, exact marks, percentage and time.</p>';
  return `<div class="point-detail" role="status"><strong>${esc(selected.examLabel||'Exam')}</strong><span>${esc(isoDate(selected.submittedAt).slice(0,10))} · ${selected.score}/${selected.total} marks · ${percentage(selected)}% · ${selected.minutes} min</span></div>`;
}

function teacherEntries(rows,studentId){
 const items=rows.slice().reverse().map(s=>{const editing=state.editingEntryId===s.id;const classId=classFor(s);const form=editing?`<form id="teacher-entry-form" data-student-id="${esc(studentId)}" data-entry-id="${esc(s.id)}" class="entry-form"><div class="fields"><label>Class<select name="classId">${(state.students.find(x=>x.id===studentId)?.classIds||[]).map(id=>opt(id,className(id),classId)).join('')}</select></label><label>Marks earned<input name="score" type="number" min="0" max="300" required value="${esc(s.score)}"></label><label>Total marks<input name="total" type="number" min="1" max="300" required value="${esc(s.total)}"></label><label>Time (minutes)<input name="minutes" type="number" min="1" max="1440" required value="${esc(s.minutes)}"></label><label class="wide">Questions for class<textarea name="questions" rows="2">${esc((s.questions||[]).join(','))}</textarea></label></div><div class="form-actions"><button class="btn" type="submit">Save correction</button>${btn('Cancel','cancel-entry','','secondary')}</div></form>`:'';return `<div class="entry"><div class="item"><div><strong>${esc(s.examLabel||assignmentTitle(s))}</strong><p class="small muted">${esc(className(classId))} · ${s.score}/${s.total} marks · ${percentage(s)}% · ${s.minutes} min</p><p class="small muted">Questions: ${s.questions?.length?esc(s.questions.join(', ')):'None'}</p></div>${btn(editing?'Editing':'Edit entry','edit-entry',`data-id="${esc(s.id)}"`,'secondary')}</div>${form}</div>`;}).join('');return card('Exam entries',items||'<div class="empty">No exam entries for this selection.</div>');
}
function progressPanel(teacher){
 const student=teacher?state.selectedStudent:me(),all=state.submissions.filter(s=>s.studentId===student).sort(sortDate);
 const classIds=teacher?(state.students.find(x=>x.id===student)?.classIds||[]):(state.profile?.classIds||[]);
 const classFilter=state.progressClass;
 const classRows=all.filter(s=>classFilter==='all'||classFor(s)===classFilter);
 const papers=[...new Set(classRows.map(s=>String(s.paper||'')).filter(Boolean))].sort();
 const rows=classRows.filter(s=>state.paper==='all'||String(s.paper)===state.paper);
 const avg=rows.length?Math.round(rows.reduce((a,s)=>a+percentage(s),0)/rows.length):'—';
 const time=rows.length?Math.round(rows.reduce((a,s)=>a+Number(s.minutes),0)/rows.length):'—';
 const studentSelect=teacher?`<label>Student<select data-change="selectedStudent">${state.students.map(s=>opt(s.id,s.name,student)).join('')}</select></label>`:'';
 return `<div class="filters">${studentSelect}<label>Class / level<select data-change="progressClass">${opt('all','All levels',classFilter)}${classIds.map(id=>opt(id,`${className(id)} · ${levelName(levelOf(id))}`,classFilter)).join('')}</select></label><label>Paper<select data-change="paper">${opt('all','All papers',state.paper)}${papers.map(p=>opt(p,`Paper ${p}`,state.paper)).join('')}</select></label><label>Mark view<select data-change="markView">${opt('percent','Percentage',state.markView)}${opt('marks','Marks earned',state.markView)}</select></label></div><div class="stats">${stat('Average mark',avg==='—'?avg:avg+'%')}${stat('Average time',time==='—'?time:time+' min','Reported time')}${stat('Results',rows.length)}</div><div class="grid equal">${card(state.markView==='marks'?'Marks earned over time':'Percentage over time',chart(rows,state.markView,'Marks')+pointDetails(rows,state.markView))}${card('Time over time',chart(rows,'minutes','Minutes taken')+pointDetails(rows,'minutes'))}</div><p class="helper">Tap a point for the exact result. Time is shown as reported; your teacher decides if it is okay.</p>${teacher?`<div class="entries-wrap">${teacherEntries(rows,student)}</div>`:''}`;
}
function teacherToday(){const due=state.assignments.filter(a=>a.dueDate===today()),needs=due.flatMap(a=>state.students.filter(s=>s.classIds?.includes(a.classId)).filter(s=>!resultFor(a,s.id)).map(s=>({a,s}))),recent=state.submissions.slice().sort((a,b)=>-sortDate(a,b)).slice(0,8);return `<div class="stats">${stat('Due today',due.length,'Assigned exams')}${stat('Submitted today',due.reduce((n,a)=>n+state.students.filter(s=>resultFor(a,s.id)).length,0))}${stat('Questions waiting',questionGroups(state.submissions).filter(q=>!state.questionStatus[q.id]).length)}</div><div class="grid">${card('Today’s exams',due.map(a=>{const count=state.students.filter(s=>resultFor(a,s.id)).length,total=state.students.filter(s=>s.classIds?.includes(a.classId)).length;return `<div class="item"><div><div class="eyebrow">${esc(className(a.classId))}</div><h3>${esc(assignmentTitle(a))}</h3><p class="small muted">${count} of ${total} submitted</p></div><span class="pill">${dateLabel(a.dueDate)}</span></div>`;}).join('')||'<div class="empty">Nothing due today.</div>')}${card('Still waiting for',needs.map(x=>`<div class="item"><div><strong>${esc(x.s.name)}</strong><div class="small muted">${esc(assignmentTitle(x.a))}</div></div></div>`).join('')||'<div class="empty">Everyone is caught up.</div>')}</div><div style="margin-top:18px">${card('Recent results',`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Exam</th><th>Marks</th><th>Time</th><th>Questions</th></tr></thead><tbody>${recent.map(s=>`<tr><td>${esc(nameFor(s.studentId))}</td><td>${esc(s.examLabel)}</td><td>${s.score}/${s.total}</td><td>${s.minutes} min</td><td>${s.questions?.length||0}</td></tr>`).join('')}</tbody></table></div>`)}</div>`;}

function blankScheduleRow(){const level=levelOf(state.scheduleClass);return {paper:String(LEVELS[level]?.papers[0]||''),year:String(new Date().getFullYear()),session:'jun',variant:'1'};}
function scheduledEditor(a,level){
 if(!a)return '';
 const session=a.session||'jun',variant=session==='mar'?2:Number(a.variant)||1,submitted=state.students.filter(s=>resultFor(a,s.id)).length;
 return card('Edit scheduled exam',`<form id="assignment-form" data-id="${esc(a.id)}" data-class="${esc(a.classId)}"><div class="fields"><label>Due date<input name="dueDate" type="date" required value="${esc(a.dueDate)}"></label><label>Year<select name="year">${years().map(y=>opt(y,y,a.year)).join('')}</select></label><label>Session<select name="session" data-edit-session>${Object.entries(SESSIONS).map(([x,y])=>opt(x,y,session)).join('')}</select></label><label>Paper<select name="paper">${(LEVELS[level]?.papers||[]).map(x=>opt(x,`Paper ${x}`,a.paper)).join('')}</select></label><label>Variant<select name="variant">${variants(session).map(x=>opt(x,`Variant ${x}`,variant)).join('')}</select></label></div>${submitted?`<p class="helper">${submitted} student${submitted===1?' has':'s have'} already submitted. Their saved results and questions will remain attached.</p>`:''}<div class="form-actions"><button class="btn" type="submit">Save exam changes</button>${btn('Cancel','cancel-edit-assignment','','secondary')}</div></form>`);
}
function schedulePanel(){
 const c=state.classes.find(x=>x.id===state.scheduleClass),level=c?.level;
 if(!state.scheduleRows.length)state.scheduleRows=[blankScheduleRow()];
 const rows=state.scheduleRows.map((r,i)=>{const paper=LEVELS[level]?.papers.includes(Number(r.paper))?Number(r.paper):LEVELS[level]?.papers[0],year=Number(r.year),session=r.session||'jun',variant=session==='mar'?2:Number(r.variant)||1,key=examKey(level,paper,year,session,variant),total=totalFor(c?.id,key,level,paper,year);return `<div class="exam-row" data-row="${i}"><div class="fields"><label>Year<select data-row="${i}" data-field="year">${years().map(y=>opt(y,y,year)).join('')}</select></label><label>Session<select data-row="${i}" data-field="session">${Object.entries(SESSIONS).map(([x,y])=>opt(x,y,session)).join('')}</select></label><label>Paper<select data-row="${i}" data-field="paper">${(LEVELS[level]?.papers||[]).map(p=>opt(p,`Paper ${p}`,paper)).join('')}</select></label><label>Variant<select data-row="${i}" data-field="variant">${variants(session).map(v=>opt(v,`Variant ${v}`,variant)).join('')}</select></label></div><div class="row" style="justify-content:space-between"><strong>${esc(examTitle(level,paper,year,session,variant))}</strong>${btn('Remove','remove-row',`data-row="${i}"`,'ghost')}</div><p class="small muted">${total?`${total} marks`:'Students enter their total marks'} </p></div>`;}).join('');
 const scheduled=state.assignments.filter(a=>a.classId===c?.id).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
 const editing=scheduled.find(a=>a.id===state.editingAssignment),deleting=scheduled.find(a=>a.id===state.deletingAssignment);
 const scheduledRows=scheduled.map(a=>`<div class="item"><div><div class="eyebrow">${dateLabel(a.dueDate)}</div><h3>${esc(assignmentTitle(a))}</h3></div><div class="actions"><span class="pill">${state.students.filter(s=>resultFor(a,s.id)).length} submitted</span>${btn('Edit','edit-assignment',`data-id="${esc(a.id)}"`,'secondary')}${btn('Delete','ask-delete-assignment',`data-id="${esc(a.id)}"`,'danger')}</div></div>`).join('')||'<div class="empty">Nothing scheduled yet.</div>';
 const deleteCard=deleting?card(`Delete ${esc(assignmentTitle(deleting))}?`,`<p>This removes the assignment from the schedule. Student results that were already submitted will stay in their history.</p><div class="form-actions">${btn('Delete scheduled exam','confirm-delete-assignment',`data-id="${esc(deleting.id)}" data-class="${esc(deleting.classId)}"`,'danger')}${btn('Keep scheduled exam','cancel-delete-assignment','','secondary')}</div>`):'';
 return `<div class="stack">${card('Schedule exams',`<div class="fields"><label>Class<select data-change="scheduleClass">${state.classes.map(x=>opt(x.id,`${x.name} · ${levelName(x.level)}`,state.scheduleClass)).join('')}</select></label><label>Due date<input type="date" data-change="scheduleDate" value="${esc(state.scheduleDate)}"></label></div>${level?`<p class="helper">Add several exams to this date, then schedule them together for everyone in ${esc(c.name)}.</p>${rows}<div class="form-actions">${btn('+ Add exam','add-row','','secondary')}${btn(`Schedule ${state.scheduleRows.length} exam${state.scheduleRows.length===1?'':'s'}`,'save-schedule')}</div>`:'<p class="empty">Set this class’s level first in Classes.</p>'}`)}${card('Scheduled for this class',scheduledRows)}${scheduledEditor(editing,level)}${deleteCard}</div>`;
}
function classPanel(){
 const c=state.classes.find(x=>x.id===state.selectedClass),selected=state.students.find(s=>s.id===state.invitePreview),edit=state.students.find(s=>s.id===state.editingStudent),deleting=state.students.find(s=>s.id===state.deletingStudent);
 const classmates=state.students.filter(s=>(s.classIds||[]).includes(c?.id));
 const ranked=classmates.map(s=>{const results=state.submissions.filter(x=>x.studentId===s.id&&classFor(x)===c?.id);return {student:s,results,average:results.length?Math.round(results.reduce((n,x)=>n+percentage(x),0)/results.length):null};}).sort((a,b)=>(b.average??-1)-(a.average??-1)||b.results.length-a.results.length);
 const roster=classmates.map(s=>`<div class="item"><div><strong>${esc(s.name)}</strong><p class="small muted">${esc((s.classIds||[]).map(className).join(', '))} · ${s.authUid?'Connected':'Invitation ready'}</p></div><div class="actions">${btn('View student','edit-student',`data-id="${esc(s.id)}"`,'secondary')}${!s.authUid?btn('Invitation','show-invite',`data-id="${esc(s.id)}"`,'secondary'):''}</div></div>`).join('')||'<div class="empty">No students in this class yet.</div>';
 const choices=state.classes.map(x=>`<label class="class-choice"><input type="checkbox" name="classIds" value="${esc(x.id)}" ${(edit?.classIds||[]).includes(x.id)?'checked':''}><span>${esc(x.name)} · ${levelName(x.level)}</span></label>`).join('');
 return `<div class="stack">${card('Classes',`<div class="filters"><label>Class<select data-change="selectedClass">${state.classes.map(x=>opt(x.id,x.name,state.selectedClass)).join('')}</select></label>${btn('+ Add class','show-add-class','','secondary')}</div>${state.showAddClass?`<form id="class-form"><div class="fields"><label>Class name<input name="name" required maxlength="80" placeholder="AS Group A"></label><label>Level<select name="level">${levelOptions('as')}</select></label></div><button class="btn" type="submit">Create class</button></form>`:''}`)}${c?`${card(`${esc(c.name)} · ${levelName(c.level)}`,`<div class="row" style="justify-content:space-between"><p class="muted small">${classmates.length} students</p>${btn('+ Add student','show-add-student','','secondary')}</div>${!c.level?`<form id="class-level-form" data-id="${esc(c.id)}"><div class="fields"><label>Set level for this existing class<select name="level">${levelOptions('olevel')}</select></label></div><button class="btn" type="submit">Save class level</button></form>`:''}${state.showAddStudent?`<form id="student-form" data-class="${esc(c.id)}"><div class="fields"><label>Student name<input name="name" required maxlength="80"></label></div><button class="btn" type="submit">Add student and make invitation</button></form>`:''}${roster}`)}${selected&&!selected.authUid?card(`Invitation for ${esc(selected.name)}`,`<p class="muted small">Share this private link with this student.</p><label>Invitation link<input id="invite-link" readonly value="${esc(inviteLink(selected))}"></label><div class="form-actions">${btn('Copy link','copy-invite')}</div>`):''}${edit?card(`Edit ${esc(edit.name)}`,`<form id="membership-form" data-id="${esc(edit.id)}"><div class="fields"><label>Name<input name="name" required maxlength="80" value="${esc(edit.name)}"></label><label>Student level<select name="subject">${levelOptions(edit.subject)}</select></label></div><p class="helper">Choose every class this student attends.</p><div class="class-choices">${choices}</div><div class="form-actions"><button class="btn" type="submit">Save student</button>${btn('Delete student','ask-delete-student',`data-id="${esc(edit.id)}"`,'danger')}${btn('Close','close-student','','ghost')}</div></form>`):''}${deleting?card(`Delete ${esc(deleting.name)}?`,`<p>This permanently removes the student, all their submitted results and all their saved questions. This cannot be undone.</p><div class="form-actions">${btn('Delete student permanently','confirm-delete-student',`data-id="${esc(deleting.id)}"`,'danger')}${btn('Keep student','cancel-delete-student','','secondary')}</div>`):''}${card('Class leaderboard',ranked.map((x,i)=>`<div class="item"><div><strong>${i+1}. ${esc(x.student.name)}</strong><p class="small muted">${x.results.length} exams completed</p></div><span class="pill">${x.average===null?'—':x.average+'%'} average</span></div>`).join('')||'<div class="empty">Results will appear here.</div>')}`:''}</div>`;
}
function inReportRange(value){const d=String(value||'').slice(0,10),from=state.reportFrom||'0000-01-01',to=state.reportTo||today();return !!d&&d>=from&&d<=to;}
function avgOf(rows,key){return rows.length?Math.round(rows.reduce((n,x)=>n+key(x),0)/rows.length):null;}
function reportControls(){return `<section class="card report-controls"><h2>Build a report</h2><div class="filters"><label>Report type<select data-change="reportType">${opt('student','Individual student',state.reportType)}${opt('class','Whole class',state.reportType)}</select></label>${state.reportType==='student'?`<label>Student<select data-change="reportStudent">${state.students.map(s=>opt(s.id,s.name,state.reportStudent)).join('')}</select></label>`:`<label>Class<select data-change="reportClass">${state.classes.map(c=>opt(c.id,c.name,state.reportClass)).join('')}</select></label>`}<label>From<input type="date" data-change="reportFrom" value="${esc(state.reportFrom)}"></label><label>To<input type="date" data-change="reportTo" value="${esc(state.reportTo||today())}"></label></div><div class="form-actions report-actions">${btn('Print / Save PDF','print-report')}${btn('Download spreadsheet','export-report','','secondary')}</div></section>`;}
function individualReport(){
 const student=state.students.find(s=>s.id===state.reportStudent);
 if(!student)return '<div class="empty">Choose a student.</div>';
 const rows=state.submissions.filter(s=>s.studentId===student.id&&inReportRange(isoDate(s.submittedAt))).sort(sortDate);
 const assignments=state.assignments.filter(a=>(student.classIds||[]).includes(a.classId)&&inReportRange(a.dueDate));
 const completed=assignments.filter(a=>resultFor(a,student.id)),missing=assignments.filter(a=>a.dueDate<=today()&&!resultFor(a,student.id));
 const avg=avgOf(rows,percentage),time=avgOf(rows,x=>Number(x.minutes));
 const recent=rows.slice(-5),previous=rows.slice(-10,-5),change=recent.length&&previous.length?avgOf(recent,percentage)-avgOf(previous,percentage):null;
 const papers=[...new Set(rows.map(x=>Number(x.paper)).filter(Boolean))].sort((a,b)=>a-b);
 const paperSummary=papers.map(p=>{const r=rows.filter(x=>Number(x.paper)===p);return `<div class="item"><strong>Paper ${p}</strong><span>${avgOf(r,percentage)}% average · ${avgOf(r,x=>Number(x.minutes))} min · ${r.length} result${r.length===1?'':'s'}</span></div>`;}).join('')||'<div class="empty">No paper results in this period.</div>';
 const questions=rows.flatMap(x=>(x.questions||[]).map(q=>({q,exam:x.examLabel})))
 const resultsTable=`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Class</th><th>Exam</th><th>Mark</th><th>Time</th><th>Questions</th></tr></thead><tbody>${rows.slice().reverse().map(x=>`<tr><td>${esc(isoDate(x.submittedAt).slice(0,10))}</td><td>${esc(className(classFor(x)))}</td><td>${esc(x.examLabel||assignmentTitle(x))}</td><td>${x.score}/${x.total} (${percentage(x)}%)</td><td>${x.minutes} min</td><td>${esc((x.questions||[]).join(', ')||'—')}</td></tr>`).join('')}</tbody></table></div>`;
 return `<section id="report-output" class="report-output"><div class="report-heading"><div><div class="eyebrow">Individual student report</div><h1>${esc(student.name)}</h1><p class="muted">${dateLabel(state.reportFrom)} to ${dateLabel(state.reportTo||today())}</p></div><div class="brand print-brand">${esc(state.branding.title)}</div></div><div class="stats">${stat('Average mark',avg===null?'—':avg+'%')}${stat('Average time',time===null?'—':time+' min')}${stat('Improvement',change===null?'—':`${change>=0?'+':''}${change}%`,'Last 5 vs previous 5')}</div><div class="stats">${stat('Results',rows.length)}${stat('Assignments completed',completed.length)}${stat('Missing',missing.length)}</div><div class="grid equal">${card('Percentage progress',chart(rows,'percent','Percentage'))}${card('Time progress',chart(rows,'minutes','Minutes'))}</div>${card('Performance by paper',paperSummary)}${card('Missing assignments',missing.map(a=>`<div class="item"><div><strong>${esc(assignmentTitle(a))}</strong><p class="small muted">${esc(className(a.classId))} · Due ${dateLabel(a.dueDate)}</p></div></div>`).join('')||'<div class="empty">No missing assignments in this period.</div>')}${card('Questions requested',questions.map(x=>`<div class="item"><strong>${esc(x.q)}</strong><span class="small muted">${esc(x.exam)}</span></div>`).join('')||'<div class="empty">No questions requested in this period.</div>')}${card('Detailed results',resultsTable)}</section>`;
}
function classReport(){
 const c=state.classes.find(x=>x.id===state.reportClass);
 if(!c)return '<div class="empty">Choose a class.</div>';
 const students=state.students.filter(s=>(s.classIds||[]).includes(c.id)),assignments=state.assignments.filter(a=>a.classId===c.id&&inReportRange(a.dueDate));
 const rows=state.submissions.filter(s=>classFor(s)===c.id&&inReportRange(isoDate(s.submittedAt)));
 const due=assignments.filter(a=>a.dueDate<=today()),expected=due.length*students.length,completed=due.reduce((n,a)=>n+students.filter(s=>resultFor(a,s.id)).length,0);
 const metrics=students.map(student=>{const r=rows.filter(x=>x.studentId===student.id),done=due.filter(a=>resultFor(a,student.id)).length;return {student,rows:r,done,missing:Math.max(0,due.length-done),avg:avgOf(r,percentage),time:avgOf(r,x=>Number(x.minutes))};}).sort((a,b)=>(b.avg??-1)-(a.avg??-1));
 const questions=questionGroups(rows).sort((a,b)=>b.students.size-a.students.size);
 const table=`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Completed</th><th>Missing</th><th>Average</th><th>Average time</th></tr></thead><tbody>${metrics.map(x=>`<tr><td>${esc(x.student.name)}</td><td>${x.done}/${due.length}</td><td>${x.missing}</td><td>${x.avg===null?'—':x.avg+'%'}</td><td>${x.time===null?'—':x.time+' min'}</td></tr>`).join('')}</tbody></table></div>`;
 const missing=due.flatMap(a=>students.filter(s=>!resultFor(a,s.id)).map(s=>({a,s})))
 return `<section id="report-output" class="report-output"><div class="report-heading"><div><div class="eyebrow">Class report · ${esc(levelName(c.level))}</div><h1>${esc(c.name)}</h1><p class="muted">${dateLabel(state.reportFrom)} to ${dateLabel(state.reportTo||today())}</p></div><div class="brand print-brand">${esc(state.branding.title)}</div></div><div class="stats">${stat('Students',students.length)}${stat('Completion',expected?Math.round(100*completed/expected)+'%':'—',`${completed} of ${expected}`)}${stat('Class average',avgOf(rows,percentage)===null?'—':avgOf(rows,percentage)+'%')}</div>${card('Student comparison',table)}${card('Missing assignments',missing.map(x=>`<div class="item"><div><strong>${esc(x.s.name)}</strong><p class="small muted">${esc(assignmentTitle(x.a))} · Due ${dateLabel(x.a.dueDate)}</p></div></div>`).join('')||'<div class="empty">No missing assignments in this period.</div>')}${card('Most requested questions',questions.slice(0,20).map(q=>`<div class="item"><div><strong>${esc(q.label)}</strong><p class="small muted">${esc(q.exam)}</p></div><span class="pill">${q.students.size} student${q.students.size===1?'':'s'}</span></div>`).join('')||'<div class="empty">No questions requested in this period.</div>')}</section>`;
}
function reportsPanel(){return `<div class="stack">${reportControls()}${state.reportType==='class'?classReport():individualReport()}</div>`;}
function reportRows(){
 if(state.reportType==='student'){const student=state.students.find(s=>s.id===state.reportStudent);return state.submissions.filter(s=>s.studentId===student?.id&&inReportRange(isoDate(s.submittedAt))).sort(sortDate).map(s=>[isoDate(s.submittedAt).slice(0,10),student.name,className(classFor(s)),s.examLabel||assignmentTitle(s),s.paper,s.score,s.total,percentage(s),s.minutes,(s.questions||[]).join(' ')]);}
 const c=state.classes.find(x=>x.id===state.reportClass);return state.submissions.filter(s=>classFor(s)===c?.id&&inReportRange(isoDate(s.submittedAt))).sort(sortDate).map(s=>[isoDate(s.submittedAt).slice(0,10),nameFor(s.studentId),c.name,s.examLabel||assignmentTitle(s),s.paper,s.score,s.total,percentage(s),s.minutes,(s.questions||[]).join(' ')]);
}
function downloadReport(){const header=['Date','Student','Class','Exam','Paper','Mark','Total','Percentage','Minutes','Questions'],cell=v=>`"${String(v??'').replaceAll('"','""')}"`,csv=[header,...reportRows()].map(row=>row.map(cell).join(',')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a'),label=state.reportType==='student'?nameFor(state.reportStudent):className(state.reportClass);a.href=url;a.download=`${label.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'report'}-${state.reportFrom}-to-${state.reportTo||today()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

function settingsPanel(){return `<div class="stack">${card('Website title',`<p class="muted small">This title appears at the top left for you and your students.</p><form id="branding-form"><div class="fields"><label>Title<input name="title" required maxlength="60" value="${esc(state.branding.title)}"></label><label>Quote under the title<input name="subtitle" maxlength="120" value="${esc(state.branding.subtitle)}"></label></div><button class="btn" type="submit">Save title</button></form>`)}${importPanel()}</div>`;}
function importPanel(){if(state.students.length)return card('Old results imported','<p class="muted small">Your earlier student records are in this new private layout. Keep your downloaded backup in a safe place.</p>');const data=state.importData;return card('Bring in your old results',`<p class="muted small">Choose the private backup downloaded from Cloud Shell. The file is read in this browser; do not upload it to GitHub. Old passcodes are not imported.</p><div class="upload"><label>Backup file<input id="backup-file" type="file" accept="application/json,.json"></label></div>${data?`<p class="helper">Found ${data.students.length} students and ${data.submissions.length} results. No email entry is needed. After import, open Students to copy each private invitation.</p><div class="form-actions">${btn('Import students and results','import-backup')}</div>`:''}`);}
function render(){document.title=state.branding.title||'Past Paper Tracker';if(!state.user){root.innerHTML=authScreen();return;}if(!state.teacher&&!state.user.emailVerified){root.innerHTML=verifyScreen();return;}if(!state.teacher&&!state.profile){root.innerHTML=claimScreen();return;}if(!state.teacher&&state.detail){const d=state.detail;root.innerHTML=top()+`<div class="hero"><h1>${d.type==='receipt'?'Your receipt':d.type==='delete'?'Delete submission?':'Your result'}</h1></div>`+(d.type==='receipt'?receipt(d.id):d.type==='delete'?card('Delete this result',`<p>This removes the result and its questions from your record.</p><div class="form-actions">${btn('Delete submission','confirm-delete',`data-id="${esc(d.id)}"`,'danger')}${btn('Keep it','close-detail','','secondary')}</div>`):resultForm(d.id))+'</div>';return;}let body=top();const name=state.teacher?'Your class, at a glance.':`Hi, ${(state.profile?.name||'student').split(' ')[0]}.`;body+=`<div class="hero"><div><div class="eyebrow">${state.teacher?'Teacher workspace':'Student workspace'} · ${dateLabel(today())}</div><h1>${state.tab==='today'?esc(name):state.teacher?{schedule:'Plan the next practice.',questions:'Solve the hard questions.',progress:'See how marks and time change.',reports:'Reports you can print or export.',roster:'Your classes.',settings:'Make this space yours.'}[state.tab]:{history:'Your work is saved.',questions:'Questions for class.',progress:'Your progress.'}[state.tab]}</h1></div>${btn('Refresh','refresh','','secondary')}</div>${tabs()}${state.notice?`<div class="notice" role="status">${esc(state.notice)}</div>`:''}${state.error?`<div class="notice error" role="alert">${esc(state.error)}</div>`:''}`;if(state.teacher){body+=state.tab==='today'?teacherToday():state.tab==='schedule'?schedulePanel():state.tab==='questions'?questionPanel(true):state.tab==='progress'?progressPanel(true):state.tab==='reports'?reportsPanel():state.tab==='roster'?classPanel():settingsPanel();}else{body+=state.tab==='today'?studentToday():state.tab==='history'?studentHistory():state.tab==='questions'?questionPanel(false):progressPanel(false);}body+='</div>';root.innerHTML=body;}

function decodeFirestore(v){if(!v||typeof v!=='object')return null;if('nullValue'in v)return null;if('stringValue'in v)return v.stringValue;if('integerValue'in v)return Number(v.integerValue);if('doubleValue'in v)return Number(v.doubleValue);if('booleanValue'in v)return v.booleanValue;if('timestampValue'in v)return v.timestampValue;if('arrayValue'in v)return(v.arrayValue.values||[]).map(decodeFirestore);if('mapValue'in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,decodeFirestore(x)]));return null;}
function parseBackup(fileData){if(!fileData?.name?.endsWith('/documents/exam-tracker/data')||!fileData.fields)throw new Error('This is not the tracker backup file.');const obj=Object.fromEntries(Object.entries(fileData.fields).map(([k,v])=>[k,decodeFirestore(v)]));if(!Array.isArray(obj.students)||!Array.isArray(obj.submissions)||!Array.isArray(obj.classes))throw new Error('The backup is missing student, class, or result records.');return obj;}
function idPart(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,100);}
function readRows(){document.querySelectorAll('[data-row][data-field]').forEach(el=>{const row=state.scheduleRows[Number(el.dataset.row)];if(row)row[el.dataset.field]=el.value;});}


root.addEventListener('click',e=>{
 const b=e.target.closest('[data-action]');if(!b)return;
 const action=b.dataset.action;state.notice='';state.error='';
 if(action==='auth-mode'){state.authMode=b.dataset.mode;render();return;}
 if(action==='signout'){run(async()=>{await signOut(auth);state.user=null;state.profile=null;state.memberId=null;state.tab='today';});return;}
 if(action==='tab'){state.tab=b.dataset.tab;state.detail=null;state.paper='all';render();return;}
 if(action==='close-detail'){state.detail=null;render();return;}
 if(action==='inspect-point'){state.selectedPoint={id:b.dataset.id,key:b.dataset.key};render();return;}
 if(action==='edit-entry'){state.editingEntryId=b.dataset.id;render();return;}
 if(action==='cancel-entry'){state.editingEntryId=null;render();return;}
 if(action==='refresh'){run(refresh);return;}
 if(action==='check-verification'){run(async()=>{await ensureVerifiedToken();await refresh();});return;}
 if(action==='resend-verification'){run(async()=>{await sendEmailVerification(auth.currentUser);state.notice='Verification email sent again.';});return;}
 if(action==='result'||action==='receipt'){state.detail={type:action,id:b.dataset.id};render();return;}
 if(action==='free-result'){state.detail={type:'result',id:''};render();return;}
 if(action==='ask-delete'){state.detail={type:'delete',id:b.dataset.id};render();return;}
 if(action==='confirm-delete'){run(async()=>{const id=b.dataset.id,s=state.submissions.find(x=>x.id===id&&x.studentId===me());if(!s)throw new Error('Result not found.');await deleteDoc(doc(db,'students',me(),'submissions',id));state.detail=null;await refresh();state.tab='history';state.notice='Submission deleted.';});return;}
 if(action==='add-row'){readRows();state.scheduleRows.push(blankScheduleRow());render();return;}
 if(action==='remove-row'){readRows();state.scheduleRows.splice(Number(b.dataset.row),1);if(!state.scheduleRows.length)state.scheduleRows.push(blankScheduleRow());render();return;}
 if(action==='save-schedule'){readRows();run(saveSchedule);return;}
 if(action==='edit-assignment'){state.editingAssignment=b.dataset.id;state.deletingAssignment='';render();return;}
 if(action==='cancel-edit-assignment'){state.editingAssignment='';render();return;}
 if(action==='ask-delete-assignment'){state.deletingAssignment=b.dataset.id;state.editingAssignment='';render();return;}
 if(action==='cancel-delete-assignment'){state.deletingAssignment='';render();return;}
 if(action==='confirm-delete-assignment'){run(async()=>{const id=b.dataset.id,classId=b.dataset.class,a=state.assignments.find(x=>x.id===id&&x.classId===classId);if(!state.teacher||!a)throw new Error('Scheduled exam not found.');await deleteDoc(doc(db,'classes',classId,'assignments',id));state.deletingAssignment='';await refresh();state.notice='Scheduled exam deleted. Existing student results were kept.';});return;}
 if(action==='print-report'){window.print();return;}
 if(action==='export-report'){downloadReport();state.notice='Spreadsheet downloaded.';render();return;}
 if(action==='show-add-class'){state.showAddClass=!state.showAddClass;render();return;}
 if(action==='show-add-student'){state.showAddStudent=!state.showAddStudent;render();return;}
 if(action==='edit-student'){state.editingStudent=b.dataset.id;state.deletingStudent='';render();return;}
 if(action==='ask-delete-student'){state.deletingStudent=b.dataset.id;render();return;}
 if(action==='cancel-delete-student'){state.deletingStudent='';render();return;}
 if(action==='confirm-delete-student'){run(async()=>{
  const id=b.dataset.id,student=state.students.find(s=>s.id===id);
  if(!state.teacher||!student)throw new Error('Student not found.');
  const refs=state.submissions.filter(s=>s.studentId===id).map(s=>doc(db,'students',id,'submissions',s.id));
  if(student.authUid)refs.push(doc(db,'members',student.authUid));
  refs.push(doc(db,'students',id));
  for(let i=0;i<refs.length;i+=450){const batch=writeBatch(db);for(const ref of refs.slice(i,i+450))batch.delete(ref);await batch.commit();}
  state.editingStudent='';state.deletingStudent='';state.invitePreview=null;await refresh();state.notice=`${student.name} and all their submissions were deleted.`;
 });return;}
 if(action==='close-student'){state.editingStudent='';state.deletingStudent='';render();return;}
 if(action==='show-invite'){state.invitePreview=b.dataset.id;render();return;}
 if(action==='show-explained'){state.showExplained=!state.showExplained;render();return;}
 if(action==='toggle-question'||action==='finish-exam'){run(async()=>{const key=action==='finish-exam'?`exam|${b.dataset.class}|${b.dataset.exam}`:b.dataset.key,explained=!state.questionStatus[key];await setDoc(doc(db,'questionStatus',encodeURIComponent(key)),{key,explained});state.questionStatus[key]=explained;state.notice=explained?'Marked explained.':'Returned to questions to explain.';});return;}
 if(action==='copy-invite'){run(async()=>{await navigator.clipboard.writeText(document.querySelector('#invite-link').value);state.notice='Invitation link copied.';});return;}
 if(action==='import-backup'){run(importLegacy);return;}
 if(action==='lock-total'){run(async()=>{const id=examTotalKey(b.dataset.class,b.dataset.exam),n=Number(document.querySelector('#lock-total').value);if(!Number.isInteger(n)||n<1||n>300)throw new Error('Enter a total from 1 to 300.');await setDoc(doc(db,'examTotals',id),{classId:b.dataset.class,examKey:b.dataset.exam,total:n});await refresh();state.notice='Total marks locked for this exam.';});return;}
});
root.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.action==='inspect-point'){e.preventDefault();e.target.click();}});
root.addEventListener('change',e=>{
 const el=e.target,key=el.dataset.change;
 if(key){state[key]=el.value;if(key==='selectedClass'){state.selectedExam='';state.invitePreview=null;state.editingStudent='';state.deletingStudent='';}if(key==='scheduleClass'){state.scheduleRows=[blankScheduleRow()];state.editingAssignment='';state.deletingAssignment='';}if(['selectedStudent','paper','progressClass','markView'].includes(key)){state.selectedPoint=null;state.editingEntryId=null;}if(['selectedStudent','progressClass'].includes(key))state.paper='all';render();return;}
 if(el.hasAttribute('data-edit-session')){const variant=el.form?.querySelector('[name="variant"]'),current=Number(variant?.value)||1;if(variant)variant.innerHTML=variants(el.value).map(v=>opt(v,`Variant ${v}`,el.value==='mar'?2:current)).join('');return;}
 if(el.dataset.free){const type=el.dataset.free;state['free'+type[0].toUpperCase()+type.slice(1)]=el.value;if(type==='class')state.freePaper='';if(type==='session'&&el.value==='mar')state.freeVariant='2';render();return;}
 if(el.dataset.row!==undefined&&el.dataset.field){readRows();if(el.dataset.field==='session'&&el.value==='mar')state.scheduleRows[Number(el.dataset.row)].variant='2';render();return;}
 if(el.id==='backup-file'){const file=el.files?.[0];if(!file)return;run(async()=>{state.importData=parseBackup(JSON.parse(await file.text()));state.notice=`Backup checked: ${state.importData.students.length} students and ${state.importData.submissions.length} results.`;});}
});
root.addEventListener('submit',e=>{
 e.preventDefault();const form=e.target,values=new FormData(form);
 if(form.id==='auth-form'){run(async()=>{const email=emailKey(values.get('email')),password=String(values.get('password')||'');if(state.authMode==='reset'){await sendPasswordResetEmail(auth,email);state.notice='Password reset email sent if this account exists.';}else if(state.authMode==='signup'){const credential=await createUserWithEmailAndPassword(auth,email,password);await sendEmailVerification(credential.user);state.notice='Verification email sent. Open it before returning here.';}else await signInWithEmailAndPassword(auth,email,password);});return;}
 if(form.id==='claim-form'){run(async()=>{state.inviteUrl=String(values.get('invite')||'').trim();const url=new URL(state.inviteUrl),raw=new URLSearchParams(url.hash.slice(1)).get('invite')||'',split=raw.indexOf('.');if(url.origin!==location.origin||split<1)throw new Error('Use the full invitation link from your teacher.');state.invite={studentId:raw.slice(0,split),code:raw.slice(split+1)};await ensureVerifiedToken();const batch=writeBatch(db),profile=doc(db,'students',state.invite.studentId),member=doc(db,'members',state.user.uid);batch.update(profile,{authUid:state.user.uid,email:emailKey(state.user.email),claimProof:state.invite.code,inviteCode:deleteField()});batch.set(member,{studentId:state.invite.studentId,email:emailKey(state.user.email)});await batch.commit();history.replaceState(null,'',location.pathname+location.search);state.invite=null;state.inviteUrl='';await refresh();state.notice='Your account is connected to your earlier work.';});return;}
 if(form.id==='result-form'){run(async()=>{
  const assignment=state.assignments.find(a=>a.id===form.dataset.assignment),old=state.submissions.find(s=>s.id===form.dataset.id&&s.studentId===me());
  const classId=assignment?.classId||String(values.get('classId')||old?.classId||classFor(old||{})||state.freeClass),level=levelOf(classId);
  const year=Number(assignment?.year||values.get('year')||old?.year),session=assignment?.session||String(values.get('session')||old?.session||''),paper=Number(assignment?.paper||values.get('paper')||old?.paper),variant=session==='mar'?2:Number(assignment?.variant||values.get('variant')||old?.variant);
  if(!LEVELS[level]||!LEVELS[level].papers.includes(paper)||!years().includes(year)||!variants(session).includes(variant))throw new Error('Choose a valid class and exam.');
  const key=examKey(level,paper,year,session,variant),fixed=totalFor(classId,key,level,paper,year),total=Number(values.get('total')),score=Number(values.get('score')),minutes=Number(values.get('minutes'));
  if(!Number.isInteger(total)||total<1||total>300||fixed&&total!==fixed||!Number.isInteger(score)||score<0||score>total||!Number.isInteger(minutes)||minutes<1||minutes>1440)throw new Error('Check your mark, total marks and actual minutes taken.');
  const questions=parseQuestions(values.get('questions')),id=old?.id||assignment?.id||`free_${classId}_${key}`;
  const payload={assignmentId:old?.id?.startsWith('free_')||old?.id?.startsWith('legacy-')?null:assignment?.id||null,classId,examKey:key,examLabel:examTitle(level,paper,year,session,variant),subject:level,paper,year,session,variant,score,total,minutes,questions,submittedAt:serverTimestamp()};
  await setDoc(doc(db,'students',me(),'submissions',id),payload,{merge:!!old});state.detail=null;await refresh();state.tab='history';state.notice='Result saved. You can find it in My submissions.';
 });return;}
 if(form.id==='teacher-entry-form'){run(async()=>{
  const studentId=form.dataset.studentId,id=form.dataset.entryId,s=state.submissions.find(x=>x.id===id&&x.studentId===studentId);if(!state.teacher||!s)throw new Error('Result not found.');
  const total=Number(values.get('total')||s.total),score=Number(values.get('score')),minutes=Number(values.get('minutes'));
  if(!Number.isInteger(total)||total<1||total>300||!Number.isInteger(score)||score<0||score>total||!Number.isInteger(minutes)||minutes<1||minutes>1440)throw new Error('Check marks and minutes.');
  const update={score,total,minutes,questions:parseQuestions(values.get('questions'))};
  if(values.get('classId'))update.classId=String(values.get('classId'));
  await setDoc(doc(db,'students',studentId,'submissions',id),update,{merge:true});await refresh();state.editingEntryId=null;state.notice='Entry corrected. The student can see it after refreshing.';
 });return;}
 if(form.id==='assignment-form'){run(async()=>{
  const id=form.dataset.id,classId=form.dataset.class,a=state.assignments.find(x=>x.id===id&&x.classId===classId),c=state.classes.find(x=>x.id===classId),level=c?.level;
  const dueDate=String(values.get('dueDate')||''),year=Number(values.get('year')),session=String(values.get('session')||''),paper=Number(values.get('paper')),variant=session==='mar'?2:Number(values.get('variant'));
  if(!a||!LEVELS[level]||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(dueDate)||!years().includes(year)||!LEVELS[level].papers.includes(paper)||!variants(session).includes(variant))throw new Error('Check the date, year, session, paper and variant.');
  const key=examKey(level,paper,year,session,variant),duplicate=state.assignments.some(x=>x.id!==id&&x.classId===classId&&x.examKey===key&&x.dueDate===dueDate);if(duplicate)throw new Error('This exam is already scheduled for that class and date.');
  await setDoc(doc(db,'classes',classId,'assignments',id),{dueDate,year,session,paper,variant,subject:level,examKey:key,examLabel:examTitle(level,paper,year,session,variant),total:totalFor(classId,key,level,paper,year)},{merge:true});state.editingAssignment='';await refresh();state.notice='Scheduled exam updated.';
 });return;}
 if(form.id==='branding-form'){run(async()=>{const title=String(values.get('title')||'').trim(),subtitle=String(values.get('subtitle')||'').trim();if(!title||title.length>60||subtitle.length>120)throw new Error('Enter a title of up to 60 characters and a quote of up to 120.');await setDoc(doc(db,'settings','app'),{title,subtitle});await refresh();state.notice='Title and quote saved.';});return;}
 if(form.id==='class-form'){run(async()=>{const name=String(values.get('name')||'').trim(),level=String(values.get('level')||'');if(!name||!LEVELS[level])throw new Error('Enter a class name and level.');const ref=doc(collection(db,'classes'));await setDoc(ref,{name,level});await refresh();state.selectedClass=ref.id;state.showAddClass=false;state.notice='Class added.';});return;}
 if(form.id==='class-level-form'){run(async()=>{const id=form.dataset.id,level=String(values.get('level'));if(!state.classes.some(c=>c.id===id)||!LEVELS[level])throw new Error('Choose a level.');await setDoc(doc(db,'classes',id),{level},{merge:true});await refresh();state.notice='Class level saved.';});return;}
 if(form.id==='student-form'){run(async()=>{const name=String(values.get('name')||'').trim(),classId=form.dataset.class,c=state.classes.find(x=>x.id===classId);if(!name||!c?.level)throw new Error('Enter a name and set the class level.');const ref=doc(collection(db,'students'));await setDoc(ref,{name,subject:c.level,classIds:[classId],inviteCode:newCode(),authUid:null,email:null});await refresh();state.invitePreview=ref.id;state.showAddStudent=false;state.notice='Student added. Their private invitation is ready.';});return;}
 if(form.id==='membership-form'){run(async()=>{const id=form.dataset.id,name=String(values.get('name')||'').trim(),subject=String(values.get('subject')),classIds=[...new Set(values.getAll('classIds').map(String))];if(!state.students.some(s=>s.id===id)||!name||!LEVELS[subject]||!classIds.length||!classIds.every(x=>state.classes.some(c=>c.id===x)))throw new Error('Enter a name, level, and at least one class.');await setDoc(doc(db,'students',id),{name,subject,classIds},{merge:true});await refresh();state.editingStudent='';state.notice='Student details saved.';});return;}
});
async function saveSchedule(){
 const c=state.classes.find(x=>x.id===state.scheduleClass),level=c?.level,date=state.scheduleDate,rows=state.scheduleRows.map(x=>({...x,paper:Number(x.paper),year:Number(x.year),variant:x.session==='mar'?2:Number(x.variant)}));
 if(!LEVELS[level]||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(date))throw new Error('Choose a class with a level and a due date.');
 const batch=writeBatch(db),seen=new Set();
 for(const r of rows){if(!LEVELS[level].papers.includes(r.paper)||!years().includes(r.year)||!variants(r.session).includes(r.variant))throw new Error('Check each year, session, paper and variant.');const key=examKey(level,r.paper,r.year,r.session,r.variant),duplicate=`${c.id}|${key}|${date}`;if(seen.has(duplicate)||state.assignments.some(a=>a.classId===c.id&&a.examKey===key&&a.dueDate===date))throw new Error('This exam is already scheduled for that class and date.');seen.add(duplicate);const ref=doc(collection(db,'classes',c.id,'assignments'));batch.set(ref,{examLabel:examTitle(level,r.paper,r.year,r.session,r.variant),examKey:key,subject:level,paper:r.paper,year:r.year,session:r.session,variant:r.variant,total:totalFor(c.id,key,level,r.paper,r.year),dueDate:date,createdAt:serverTimestamp()});}
 await batch.commit();state.scheduleRows=[blankScheduleRow()];await refresh();state.notice=`${rows.length} exam${rows.length===1?'':'s'} scheduled for ${c.name}.`;
}
async function importLegacy(){const old=state.importData;if(!old)throw new Error('Choose the backup file first.');if(state.students.length)throw new Error('Import is only available before students are added.');if(old.students.length+old.submissions.length+old.classes.length+1>490)throw new Error('This backup is too large for the one-step import.');const batch=writeBatch(db),ids=new Set(old.students.map(s=>String(s.id)));for(const c of old.classes)batch.set(doc(db,'classes',idPart(c.id)),{name:String(c.name||'Class')});for(const s of old.students){batch.set(doc(db,'students',idPart(s.id)),{name:String(s.name||'Student'),subject:String(s.subject||'olevel'),classIds:(s.classIds||[]).map(idPart),legacyId:String(s.id),inviteCode:newCode(),authUid:null,email:null});}for(const s of old.submissions){if(!ids.has(String(s.studentId)))continue;const id='legacy-'+idPart(s.id||crypto.randomUUID());batch.set(doc(db,'students',idPart(s.studentId),'submissions',id),{assignmentId:null,classId:null,examLabel:String(s.examLabel||''),examKey:String(s.examKey||''),subject:String(s.subject||''),paper:Number(s.paper)||0,year:Number(s.year)||0,session:String(s.session||''),variant:Number(s.variant)||0,score:Number(s.score)||0,total:Number(s.total)||1,minutes:Number(s.minutes)||0,questions:(s.difficultQuestions||[]).map(String),submittedAt:String(s.submittedAt||new Date().toISOString())});}batch.set(doc(db,'settings','app'),state.branding);await batch.commit();state.importData=null;await refresh();state.tab='roster';state.notice=`Imported ${old.students.length} students and ${old.submissions.length} earlier results. Old passcodes were left behind.`;}
onAuthStateChanged(auth,async user=>{state.user=user;state.teacher=user?.uid===TEACHER_UID;state.profile=null;state.error='';state.notice='';if(user&&(state.teacher||user.emailVerified)){try{if(!state.teacher)await ensureVerifiedToken();await refresh();}catch(e){state.error=friendlyError(e);}}render();});
