import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, sendEmailVerification, sendPasswordResetEmail, reload, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, doc, collection, getDoc, getDocs, setDoc, writeBatch, serverTimestamp, deleteField } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const firebaseConfig = {
  apiKey: 'AIzaSyBWQTbyCFJxLsypcyVIK5gC4-KeXnxXfEw',
  authDomain: 'past-paper-tracker-51a18.firebaseapp.com',
  projectId: 'past-paper-tracker-51a18',
  storageBucket: 'past-paper-tracker-51a18.firebasestorage.app',
  messagingSenderId: '7364242011',
  appId: '1:7364242011:web:839ff4cc39b155d3aeed7e'
};
const TEACHER_UID = 'yObDW0xHlmYFqgEcZT2xjKgVwxn1';
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const root = document.querySelector('#app');
const state = { user:null, teacher:false, profile:null, memberId:null, invite:readInvite(), inviteUrl:location.hash?location.href:'', invitePreview:null, tab:'today', authMode:'signin', busy:false, notice:'', error:'', branding:{title:'Past Paper Tracker', subtitle:'Your practice space'}, classes:[], students:[], assignments:[], submissions:[], selectedStudent:'', membershipStudent:'', paper:'all', markView:'percent', selectedPoint:null, selectedClass:'all', selectedExam:'all', questionStatus:{}, importData:null, scheduleRows:[] };
const esc = v => String(v ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const today = () => { const p = Object.fromEntries(new Intl.DateTimeFormat('en', {timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).map(x=>[x.type,x.value])); return `${p.year}-${p.month}-${p.day}`; };
const emailKey = v => String(v ?? '').trim().toLowerCase();
const btn = (label,action,extra='',kind='') => `<button type="button" class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
const card = (title,body,extra='') => `<section class="card"><div class="row" style="justify-content:space-between;margin-bottom:14px"><h2 style="margin:0">${title}</h2>${extra}</div>${body}</section>`;
const dateLabel = v => v ? new Date(v+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}) : '—';
const className = id => state.classes.find(c=>c.id===id)?.name || id;
const nameFor = id => state.students.find(s=>s.id===id)?.name || id;
const me = () => state.memberId;
function readInvite(){const raw=new URLSearchParams(location.hash.slice(1)).get('invite');if(!raw)return null;const split=raw.indexOf('.');return split>0?{studentId:raw.slice(0,split),code:raw.slice(split+1)}:null;}
function newCode(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');}
function inviteLink(s){return `${location.origin}${location.pathname}#invite=${encodeURIComponent(s.id+'.'+s.inviteCode)}`;}
const published = a => a.dueDate <= today();
const isoDate = v => v?.toDate ? v.toDate().toISOString() : String(v||'');
const sortDate = (a,b) => isoDate(a.submittedAt||a.date).localeCompare(isoDate(b.submittedAt||b.date));
function enrichSubmissions(){state.submissions=state.submissions.map(s=>{const a=state.assignments.find(x=>x.id===s.assignmentId&&x.classId===s.classId);return a?{...a,...s,total:a.total,examLabel:assignmentTitle(a),examKey:a.examKey}:s;});}

function friendlyError(e){
  const code=e?.code||'';
  if(['auth/invalid-credential','auth/wrong-password','auth/user-not-found'].includes(code)) return 'Email or password was not accepted.';
  if(code==='auth/email-already-in-use') return 'This email already has an account. Choose Sign in instead.';
  if(code==='auth/weak-password') return 'Choose a stronger password with at least 6 characters.';
  if(code==='permission-denied') return 'Firebase blocked this request. The new security rules may not be published yet.';
  return e?.message || 'Something went wrong. Please try again.';
}
function message(text,bad=false){state.notice=bad?'':text;state.error=bad?text:'';render();}
async function run(task){ if(state.busy)return;state.busy=true;state.error='';render();try{await task();}catch(e){console.error(e);state.error=friendlyError(e);}finally{state.busy=false;render();} }
async function readCollection(ref){const snap=await getDocs(ref);return snap.docs.map(d=>({id:d.id,...d.data()}));}
async function refresh(){
  const settings=await getDoc(doc(db,'settings','app'));
  state.branding=settings.exists()?{title:settings.data().title||'Past Paper Tracker',subtitle:settings.data().subtitle||''}:state.branding;
  if(state.teacher){
    state.questionStatus=Object.fromEntries((await readCollection(collection(db,'questionStatus'))).map(x=>[x.key,x.explained]));
    state.classes=await readCollection(collection(db,'classes'));
    state.students=await readCollection(collection(db,'students'));
    state.assignments=(await Promise.all(state.classes.map(c=>readCollection(collection(db,'classes',c.id,'assignments')).then(a=>a.map(x=>({...x,classId:c.id})))))).flat();
    state.submissions=(await Promise.all(state.students.map(s=>readCollection(collection(db,'students',s.id,'submissions')).then(a=>a.map(x=>({...x,studentId:s.id})))))).flat();
    enrichSubmissions();
    if(!state.selectedStudent&&state.students.length)state.selectedStudent=state.students[0].id;
  }else{
    const member=await getDoc(doc(db,'members',state.user.uid));
    if(!member.exists()){state.profile=null;state.memberId=null;state.classes=[];state.assignments=[];state.submissions=[];return;}
    state.memberId=member.data().studentId;
    const profile=await getDoc(doc(db,'students',state.memberId));
    if(!profile.exists())throw new Error('Your student record could not be found. Please ask your teacher.');
    state.profile={id:state.memberId,...profile.data()};
    state.questionStatus=Object.fromEntries((await readCollection(collection(db,'questionStatus'))).map(x=>[x.key,x.explained]));
    state.classes=(await Promise.all((state.profile.classIds||[]).map(async id=>{const x=await getDoc(doc(db,'classes',id));return x.exists()?{id,...x.data()}:null;}))).filter(Boolean);
    state.assignments=(await Promise.all(state.classes.map(c=>readCollection(collection(db,'classes',c.id,'assignments')).then(a=>a.map(x=>({...x,classId:c.id})))))).flat();
    state.submissions=(await readCollection(collection(db,'students',state.memberId,'submissions'))).map(x=>({...x,studentId:state.memberId}));
    enrichSubmissions();
  }
}
function top(){return `<div class="shell"><header class="top"><div class="brand">${esc(state.branding.title)}<small>${esc(state.branding.subtitle)}</small></div><div class="top-actions"><span class="small muted">${state.teacher?'Teacher':esc(state.profile?.name||'Student')}</span>${btn('Sign out','signout','','ghost')}</div></header>`;}
function tabs(){const options=state.teacher?[['today','Overview'],['schedule','Schedule'],['questions','Classroom questions'],['progress','Progress'],['roster','Students'],['settings','Settings']]:[['today','My assignments'],['history','My submissions'],['questions','My questions'],['progress','My progress']];return `<nav class="tabs" aria-label="Dashboard sections">${options.map(([id,label])=>`<button data-action="tab" data-tab="${id}" class="${state.tab===id?'active':''}">${label}</button>`).join('')}</nav>`;}
function authScreen(){return `<main class="auth-wrap"><section class="auth-card"><div class="eyebrow">${esc(state.branding.title)}</div><h1>${state.authMode==='signup'?'Create your account':state.authMode==='reset'?'Reset your password':'Welcome back'}</h1><p class="muted">${state.authMode==='signup'?'Use your own email and the private invitation your teacher gave you. Verify your email before viewing results.':state.authMode==='reset'?'We will email you a password reset link.':'Sign in to see your own work and progress.'}</p><form id="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required></label>${state.authMode!=='reset'?`<label>Password<input name="password" type="password" minlength="6" autocomplete="${state.authMode==='signup'?'new-password':'current-password'}" required></label>`:''}<button class="btn" type="submit" ${state.busy?'disabled':''}>${state.authMode==='signup'?'Create account':state.authMode==='reset'?'Send reset link':'Sign in'}</button></form><div class="auth-links">${state.authMode!=='signin'?btn('Sign in','auth-mode','data-mode="signin"','ghost'):''}${state.authMode!=='signup'?btn('Create account','auth-mode','data-mode="signup"','ghost'):''}${state.authMode!=='reset'?btn('Forgot password?','auth-mode','data-mode="reset"','ghost'):''}</div>${state.notice?`<div class="notice" role="status">${esc(state.notice)}</div>`:''}${state.error?`<div class="notice error" role="alert">${esc(state.error)}</div>`:''}</section></main>`;}
function verifyScreen(){return `<main class="auth-wrap"><section class="auth-card"><div class="eyebrow">One quick check</div><h1>Verify your email</h1><p class="muted">Firebase has sent a verification link to ${esc(state.user.email)}. Open that email, click the link, then return here.</p>${btn('I verified my email','check-verification')} ${btn('Send another email','resend-verification','','secondary')} ${btn('Sign out','signout','','ghost')}${state.notice?`<div class="notice">${esc(state.notice)}</div>`:''}${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}</section></main>`;}
function claimScreen(){return `<main class="auth-wrap"><section class="auth-card"><div class="eyebrow">Connect your earlier work</div><h1>Use your invitation</h1><p class="muted">Your teacher’s private link connects this email to your existing marks and questions. Open that link, or paste it below.</p><form id="claim-form"><label>Private invitation link<input name="invite" required placeholder="Paste the link your teacher gave you" value="${esc(state.inviteUrl)}"></label><button class="btn" type="submit">Connect my dashboard</button></form><div class="auth-links">${btn('Sign out','signout','','ghost')}</div>${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}</section></main>`;}
function stat(label,value,note=''){return `<div class="stat"><div class="small muted">${label}</div><strong>${value}</strong><div class="small muted">${note}</div></div>`;}
function assignmentTitle(a){return a.examLabel||`${a.subject||''} · Paper ${a.paper||''} · ${a.session||''} ${a.year||''}`;}
function studentToday(){const due=state.assignments.filter(published).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),future=state.assignments.filter(a=>!published(a)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)),submitted=new Set(state.submissions.filter(s=>s.assignmentId).map(s=>s.assignmentId));const row=a=>`<div class="item"><div><div class="eyebrow">${esc(className(a.classId))} · ${dateLabel(a.dueDate)}</div><h3>${esc(assignmentTitle(a))}</h3><p class="small muted">${a.total} marks · Paper ${esc(a.paper)}</p></div><div class="actions"><span class="pill ${submitted.has(a.id)?'':'wait'}">${submitted.has(a.id)?'Submitted':published(a)?'Due':'Upcoming'}</span>${submitted.has(a.id)?btn('View receipt','receipt',`data-id="${esc(a.id)}"`,'secondary'):published(a)?btn('Enter result','result',`data-id="${esc(a.id)}"`):''}</div></div>`;return `<div class="stats">${stat('Due so far',due.length)}${stat('Submitted',due.filter(a=>submitted.has(a.id)).length)}${stat('Coming up',future.length)}</div><div class="stack">${card('Due and submitted',due.map(row).join('')||'<div class="empty">No exams due yet.</div>')}${card('Coming up',future.map(row).join('')||'<div class="empty">No future exams scheduled yet.</div>')}</div>`;}
function receipt(id){const a=state.assignments.find(x=>x.id===id),s=state.submissions.find(x=>x.assignmentId===id);if(!a||!s)return '<div class="empty">Receipt not found.</div>';return card('Submission receipt',`<h3>${esc(assignmentTitle(a))}</h3><div class="receipt"><p><strong>${s.score}/${a.total}</strong> marks (${Math.round(s.score/a.total*100)}%)</p><p>${s.minutes} minutes</p><p>Questions: ${s.questions?.length?esc(s.questions.join(', ')):'None'}</p><p class="small muted">Saved ${esc(isoDate(s.submittedAt).slice(0,16).replace('T',' '))}</p></div><div class="form-actions">${btn('Edit result','result',`data-id="${esc(id)}"`,'secondary')}${btn('Back to assignments','tab','data-tab="today"','ghost')}</div>`);}
function resultForm(id){const a=state.assignments.find(x=>x.id===id),s=state.submissions.find(x=>x.assignmentId===id);if(!a)return '<div class="empty">Assignment not found.</div>';return card(s?'Edit result':'Submit result',`<div class="eyebrow">${esc(className(a.classId))} · ${dateLabel(a.dueDate)}</div><h3>${esc(assignmentTitle(a))}</h3><p class="small muted" style="margin-top:8px">After checking your mistakes, list only questions you still want explained in class.</p><form id="result-form" data-id="${esc(id)}"><div class="fields"><label>Mark out of ${a.total}<input name="score" type="number" min="0" max="${a.total}" step="1" required value="${s?.score??''}"></label><label>Actual time taken (minutes)<input name="minutes" type="number" min="1" max="1440" step="1" required value="${s?.minutes??''}"></label><label class="wide">Questions I still need help with<textarea name="questions" rows="3" placeholder="Example: 2(b)(ii), 4(c)">${esc((s?.questions||[]).join(', '))}</textarea></label></div><button class="btn" type="submit">Save result</button> ${btn('Cancel','tab','data-tab="today"','secondary')}</form>`);}
function studentHistory(){const rows=state.submissions.slice().sort((a,b)=>-sortDate(a,b)).map(s=>`<div class="item"><div><h3>${esc(s.examLabel||assignmentTitle(state.assignments.find(a=>a.id===s.assignmentId)||{}))}</h3><p class="small muted">${s.score}/${s.total} marks · ${s.minutes} min · ${dateLabel(isoDate(s.submittedAt).slice(0,10))}</p></div>${s.assignmentId?btn('Receipt','receipt',`data-id="${esc(s.assignmentId)}"`,'secondary'):'<span class="pill">Earlier result</span>'}</div>`).join('');return card('Your submission record',rows||'<div class="empty">Your results will appear here.</div>');}
function questionsFor(records){const groups=new Map();for(const s of records){for(const raw of (s.questions||[])){const q=String(raw).trim();if(!q)continue;const key=`${s.examKey||s.examLabel||s.assignmentId}|${q.toLowerCase().replace(/\s/g,'')}`;let item=groups.get(key);if(!item){item={key,exam:s.examLabel||assignmentTitle(state.assignments.find(a=>a.id===s.assignmentId)||{}),q,names:new Set()};groups.set(key,item);}item.names.add(s.studentId);}}return [...groups.values()].sort((a,b)=>a.exam.localeCompare(b.exam)||a.q.localeCompare(b.q,undefined,{numeric:true}));}
function questionPanel(teacher){
  let records=state.submissions;
  if(teacher&&state.selectedClass!=='all')records=records.filter(s=>s.classId===state.selectedClass||state.students.some(p=>p.id===s.studentId&&p.classIds?.includes(state.selectedClass)));
  const all=questionsFor(records),exams=[...new Set(all.map(x=>x.exam))].sort(),qq=teacher&&state.selectedExam!=='all'?all.filter(q=>q.exam===state.selectedExam):all;
  const filters=teacher?`<div class="filters"><label>Class<select data-change="selectedClass"><option value="all">All classes</option>${state.classes.map(c=>`<option value="${esc(c.id)}" ${state.selectedClass===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Exam<select data-change="selectedExam"><option value="all">All exams</option>${exams.map(x=>`<option value="${esc(x)}" ${state.selectedExam===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label></div>`:'';
  const body=filters+(qq.map(q=>`<div class="question"><div class="small muted">${esc(q.exam)}</div><div class="row" style="justify-content:space-between"><strong>Question ${esc(q.q)}</strong><span class="pill ${state.questionStatus[q.key]?'':'wait'}">${state.questionStatus[q.key]?'Explained':'To discuss'}</span></div>${teacher?`<div class="names">Asked by ${[...q.names].map(nameFor).map(esc).join(', ')}</div><div class="form-actions">${btn(state.questionStatus[q.key]?'Mark as still needed':'Mark explained','toggle-question',`data-key="${esc(q.key)}"`,'secondary')}</div>`:''}</div>`).join('')||'<div class="empty">No questions have been added for this selection.</div>');
  return card(teacher?'Questions to solve in class':'Questions you asked',body);
}
function percentage(s){return Number((100 * s.score / s.total).toFixed(1));}
function chart(rows,key,label){
  if(!rows.length)return '<div class="empty">No results yet.</div>';
  const values=rows.map(s=>key==='percent'?percentage(s):key==='marks'?Number(s.score):Number(s.minutes));
  const max=key==='percent'?100:key==='marks'?Math.max(1,...rows.map(s=>Number(s.total)||0)):Math.max(60,Math.ceil(Math.max(...values)/20)*20);
  const w=500,h=220,l=42,r=16,t=20,b=35,x=i=>l+(w-l-r)*i/Math.max(1,values.length-1),y=v=>h-b-(h-t-b)*v/max;
  const color=key==='minutes'?'#4f77ad':'#2c7047';
  const points=rows.map((s,i)=>{
    const exact=`${s.score}/${s.total} marks (${percentage(s)}%) · ${s.minutes} min`;
    const description=`${s.examLabel||'Exam'}: ${exact}`;
    const active=state.selectedPoint?.id===s.id&&state.selectedPoint?.key===key;
    return `<g class="plot-point ${active?'selected':''}" data-action="inspect-point" data-id="${esc(s.id)}" data-key="${key}" role="button" tabindex="0" aria-label="${esc(description)}"><circle cx="${x(i)}" cy="${y(values[i])}" r="15" class="point-hit"/><circle cx="${x(i)}" cy="${y(values[i])}" r="5" fill="${color}"/></g>`;
  }).join('');
  return `<svg class="chart" viewBox="0 0 ${w} ${h}" role="group" aria-label="${esc(label)}. Tap a point for its exact result."><line class="gridline" x1="${l}" y1="${y(0)}" x2="${w-r}" y2="${y(0)}"/><line class="gridline" x1="${l}" y1="${y(max/2)}" x2="${w-r}" y2="${y(max/2)}"/><line class="gridline" x1="${l}" y1="${y(max)}" x2="${w-r}" y2="${y(max)}"/><text x="2" y="${y(0)+4}">0</text><text x="2" y="${y(max/2)+4}">${max/2}</text><text x="2" y="${y(max)+4}">${max}</text><path d="M${values.map((v,i)=>`${x(i)},${y(v)}`).join(' L')}" fill="none" stroke="${color}" stroke-width="3"/>${points}<text x="${l}" y="${h-6}">${esc(isoDate(rows[0].submittedAt).slice(0,10))}</text><text x="${w-r}" y="${h-6}" text-anchor="end">${esc(isoDate(rows.at(-1).submittedAt).slice(0,10))}</text></svg>`;
}
function pointDetails(rows,key){
  const selected=state.selectedPoint?.key===key&&rows.find(s=>s.id===state.selectedPoint.id);
  if(!selected)return '<p class="helper">Tap a point to see the exam, exact marks, percentage and time.</p>';
  return `<div class="point-detail" role="status"><strong>${esc(selected.examLabel||'Exam')}</strong><span>${esc(isoDate(selected.submittedAt).slice(0,10))} · ${selected.score}/${selected.total} marks · ${percentage(selected)}% · ${selected.minutes} min</span></div>`;
}
function progressPanel(teacher){
  const student=teacher?state.selectedStudent:me(),all=state.submissions.filter(s=>s.studentId===student).sort(sortDate);
  const papers=[...new Set(all.map(s=>String(s.paper||'')).filter(Boolean))].sort();
  const rows=all.filter(s=>state.paper==='all'||String(s.paper)===state.paper);
  const avg=rows.length?Math.round(rows.reduce((a,s)=>a+percentage(s),0)/rows.length):'—';
  const time=rows.length?Math.round(rows.reduce((a,s)=>a+Number(s.minutes),0)/rows.length):'—';
  const studentSelect=teacher?`<label>Student<select data-change="selectedStudent">${state.students.map(s=>`<option value="${esc(s.id)}" ${student===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`:'';
  const view=`<label>Mark view<select data-change="markView"><option value="percent" ${state.markView==='percent'?'selected':''}>Percentage</option><option value="marks" ${state.markView==='marks'?'selected':''}>Marks earned</option></select></label>`;
  return `<div class="filters">${studentSelect}<label>Paper type<select data-change="paper"><option value="all">All papers</option>${papers.map(p=>`<option value="${esc(p)}" ${state.paper===p?'selected':''}>Paper ${esc(p)}</option>`).join('')}</select></label>${view}</div><div class="stats">${stat('Average mark',avg==='—'?avg:avg+'%')}${stat('Average time',time==='—'?time:time+' min','Actual time reported')}${stat('Results recorded',rows.length)}</div><div class="grid equal">${card(state.markView==='marks'?'Marks earned over time':'Percentage over time',chart(rows,state.markView,'Marks')+pointDetails(rows,state.markView))}${card('Time over time',chart(rows,'minutes','Minutes taken')+pointDetails(rows,'minutes'))}</div><p class="helper">Each exam may have a different total. Tap a point for marks out of the total. Time is shown as reported; the teacher decides whether it is acceptable.</p>`;
}
function teacherToday(){const due=state.assignments.filter(a=>a.dueDate===today()),needs=due.flatMap(a=>state.students.filter(s=>s.classIds?.includes(a.classId)).filter(s=>!state.submissions.some(x=>x.studentId===s.id&&x.assignmentId===a.id)).map(s=>({a,s}))),recent=state.submissions.slice().sort((a,b)=>-sortDate(a,b)).slice(0,8);return `<div class="stats">${stat('Due today',due.length,'Assigned exams')}${stat('Submitted today',state.submissions.filter(s=>due.some(a=>a.id===s.assignmentId)).length)}${stat('Questions waiting',questionsFor(state.submissions).length)}</div><div class="grid">${card('Today’s exams',due.map(a=>{const count=state.submissions.filter(s=>s.assignmentId===a.id).length,total=state.students.filter(s=>s.classIds?.includes(a.classId)).length;return `<div class="item"><div><div class="eyebrow">${esc(className(a.classId))}</div><h3>${esc(assignmentTitle(a))}</h3><p class="small muted">${count} of ${total} submitted</p></div><span class="pill">${dateLabel(a.dueDate)}</span></div>`;}).join('')||'<div class="empty">Nothing due today.</div>')}${card('Still waiting for',needs.map(x=>`<div class="item"><div><strong>${esc(x.s.name)}</strong><div class="small muted">${esc(assignmentTitle(x.a))}</div></div></div>`).join('')||'<div class="empty">Everyone is caught up.</div>')}</div><div style="margin-top:18px">${card('Recent results',`<div class="table-wrap"><table><thead><tr><th>Student</th><th>Exam</th><th>Marks</th><th>Time</th><th>Questions</th></tr></thead><tbody>${recent.map(s=>`<tr><td>${esc(nameFor(s.studentId))}</td><td>${esc(s.examLabel)}</td><td>${s.score}/${s.total}</td><td>${s.minutes} min</td><td>${s.questions?.length||0}</td></tr>`).join('')}</tbody></table></div>`)}</div>`;}
function blankScheduleRow(){const c=state.classes[0];return {classId:c?.id||'',examLabel:'',subject:'olevel',paper:'2',year:new Date().getFullYear(),session:'jun',variant:'1',total:'',dueDate:today()};}
function schedulePanel(){if(!state.scheduleRows.length)state.scheduleRows=[blankScheduleRow()];const rows=state.scheduleRows.map((r,i)=>`<div class="schedule-row"><label>Exam name<input data-row="${i}" data-field="examLabel" value="${esc(r.examLabel)}" placeholder="May/June 2024 Paper 22"></label><label>Class<select data-row="${i}" data-field="classId">${state.classes.map(c=>`<option value="${esc(c.id)}" ${r.classId===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Level<select data-row="${i}" data-field="subject"><option value="olevel" ${r.subject==='olevel'?'selected':''}>O Level</option><option value="as" ${r.subject==='as'?'selected':''}>AS Level</option><option value="a2" ${r.subject==='a2'?'selected':''}>A2 Level</option><option value="alevel" ${r.subject==='alevel'?'selected':''}>Full A Level</option><option value="combined" ${r.subject==='combined'?'selected':''}>Combined</option></select></label><label>Paper<input data-row="${i}" data-field="paper" type="number" min="1" max="9" value="${esc(r.paper)}"></label><label>Year<input data-row="${i}" data-field="year" type="number" min="2000" max="2100" value="${esc(r.year)}"></label><label>Session<select data-row="${i}" data-field="session"><option value="mar" ${r.session==='mar'?'selected':''}>March</option><option value="jun" ${r.session==='jun'?'selected':''}>May/June</option><option value="nov" ${r.session==='nov'?'selected':''}>Oct/Nov</option></select></label><label>Variant<input data-row="${i}" data-field="variant" type="number" min="1" max="9" value="${esc(r.variant)}"></label><label>Total marks<input data-row="${i}" data-field="total" type="number" min="1" max="300" value="${esc(r.total)}"></label><label>Due date<input data-row="${i}" data-field="dueDate" type="date" value="${esc(r.dueDate)}"></label>${btn('Remove','remove-row',`data-row="${i}"`,'ghost')}</div>`).join('');const future=state.assignments.slice().sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return `<div class="stack">${card('Schedule several exams',`<p class="muted small">Add one row per exam. Several rows can share the same due date.</p>${rows}<div class="form-actions">${btn('+ Add exam','add-row','','secondary')}${btn('Save schedule','save-schedule')}</div>`)}${card('Scheduled exams',future.map(a=>`<div class="item"><div><div class="eyebrow">${esc(className(a.classId))} · ${dateLabel(a.dueDate)}</div><h3>${esc(assignmentTitle(a))}</h3></div><span class="pill">${state.submissions.filter(s=>s.assignmentId===a.id).length} submitted</span></div>`).join('')||'<div class="empty">Nothing scheduled yet.</div>')}</div>`;}
function levelOptions(selected){return [['olevel','O Level'],['as','AS Level'],['a2','A2 Level'],['alevel','Full A Level'],['combined','Combined Science']].map(([value,label])=>`<option value="${value}" ${selected===value?'selected':''}>${label}</option>`).join('');}
function rosterPanel(){
  const selected=state.students.find(s=>s.id===state.invitePreview);
  const editStudent=state.students.find(s=>s.id===state.membershipStudent)||state.students[0];
  const choices=state.classes.map(c=>`<label class="class-choice"><input type="checkbox" name="classIds" value="${esc(c.id)}" ${(editStudent?.classIds||[]).includes(c.id)?'checked':''}><span>${esc(c.name)}</span></label>`).join('');
  return `<div class="stack">
    ${card('Students',`<p class="muted small">Each student gets one private invitation. They enter their own email and verify it. You do not need to collect or type their emails.</p><div class="table-wrap"><table><thead><tr><th>Name</th><th>Level</th><th>Classes</th><th>Access</th></tr></thead><tbody>${state.students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.subject)}</td><td>${esc((s.classIds||[]).map(className).join(', '))}</td><td>${s.authUid?`<span class="pill">Connected</span> <span class="small muted">${esc(s.email||'')}</span>`:btn('Show invitation','show-invite',`data-id="${esc(s.id)}"`,'secondary')}</td></tr>`).join('')}</tbody></table></div>`)}
    ${selected&&!selected.authUid?card('Private invitation for '+esc(selected.name),`<p class="muted small">Copy this link and give it only to ${esc(selected.name)}. It can connect one account to this student’s earlier work.</p><label>Invitation link<input readonly value="${esc(inviteLink(selected))}" id="invite-link"></label><div class="form-actions">${btn('Copy link','copy-invite')}</div>`):''}
    ${card('Add student',`<form id="student-form"><div class="fields"><label>Name<input name="name" required maxlength="80"></label><label>Level<select name="subject">${levelOptions('olevel')}</select></label><label>Class<select name="classId">${state.classes.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label></div><button class="btn" type="submit">Add student</button></form>`)}
    ${card('Edit level and classes',`<p class="muted small">Tick every class this student attends. They will see assignments from all selected classes.</p><form id="membership-form"><div class="fields"><label>Student<select name="studentId" data-change="membershipStudent">${state.students.map(s=>`<option value="${esc(s.id)}" ${editStudent?.id===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Level<select name="subject">${levelOptions(editStudent?.subject)}</select></label></div><div class="class-choices" role="group" aria-label="Classes">${choices}</div><div class="form-actions"><button class="btn" type="submit">Save student details</button></div></form>`)}
    ${card('Add class',`<form id="class-form"><div class="fields"><label>Class name<input name="name" required maxlength="80" placeholder="AS Level Group A"></label></div><button class="btn" type="submit">Add class</button></form>`)}
  </div>`;
}
function settingsPanel(){return `<div class="stack">${card('Website title',`<p class="muted small">This title appears at the top left for you and your students.</p><form id="branding-form"><div class="fields"><label>Title<input name="title" required maxlength="60" value="${esc(state.branding.title)}"></label><label>Small description<input name="subtitle" maxlength="80" value="${esc(state.branding.subtitle)}"></label></div><button class="btn" type="submit">Save title</button></form>`)}${importPanel()}</div>`;}
function importPanel(){if(state.students.length)return card('Old results imported','<p class="muted small">Your earlier student records are in this new private layout. Keep your downloaded backup in a safe place.</p>');const data=state.importData;return card('Bring in your old results',`<p class="muted small">Choose the private backup downloaded from Cloud Shell. The file is read in this browser; do not upload it to GitHub. Old passcodes are not imported.</p><div class="upload"><label>Backup file<input id="backup-file" type="file" accept="application/json,.json"></label></div>${data?`<p class="helper">Found ${data.students.length} students and ${data.submissions.length} results. No email entry is needed. After import, open Students to copy each private invitation.</p><div class="form-actions">${btn('Import students and results','import-backup')}</div>`:''}`);}
function render(){if(!state.user){root.innerHTML=authScreen();return;}if(!state.teacher&&!state.user.emailVerified){root.innerHTML=verifyScreen();return;}if(!state.teacher&&!state.profile){root.innerHTML=claimScreen();return;}if(!state.teacher&&state.detail){root.innerHTML=top()+`<div class="hero"><h1>${state.detail.type==='receipt'?'Your receipt':'Your result'}</h1></div>`+(state.detail.type==='receipt'?receipt(state.detail.id):resultForm(state.detail.id))+'</div>';return;}let body=top();const name=state.teacher?'Your class, at a glance.':`Hi, ${(state.profile?.name||'student').split(' ')[0]}.`;body+=`<div class="hero"><div><div class="eyebrow">${state.teacher?'Teacher workspace':'Student workspace'} · ${dateLabel(today())}</div><h1>${state.tab==='today'?esc(name):state.teacher?{schedule:'Plan the next practice.',questions:'Solve the hard questions.',progress:'See how marks and time change.',roster:'Your students.',settings:'Make this space yours.'}[state.tab]:{history:'Your work is saved.',questions:'Questions for class.',progress:'Your progress.'}[state.tab]}</h1></div>${btn('Refresh','refresh','','secondary')}</div>${tabs()}${state.notice?`<div class="notice" role="status">${esc(state.notice)}</div>`:''}${state.error?`<div class="notice error" role="alert">${esc(state.error)}</div>`:''}`;if(state.teacher){body+=state.tab==='today'?teacherToday():state.tab==='schedule'?schedulePanel():state.tab==='questions'?questionPanel(true):state.tab==='progress'?progressPanel(true):state.tab==='roster'?rosterPanel():settingsPanel();}else{body+=state.tab==='today'?studentToday():state.tab==='history'?studentHistory():state.tab==='questions'?questionPanel(false):progressPanel(false);}body+='</div>';root.innerHTML=body;}

function decodeFirestore(v){if(!v||typeof v!=='object')return null;if('nullValue'in v)return null;if('stringValue'in v)return v.stringValue;if('integerValue'in v)return Number(v.integerValue);if('doubleValue'in v)return Number(v.doubleValue);if('booleanValue'in v)return v.booleanValue;if('timestampValue'in v)return v.timestampValue;if('arrayValue'in v)return(v.arrayValue.values||[]).map(decodeFirestore);if('mapValue'in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,decodeFirestore(x)]));return null;}
function parseBackup(fileData){if(!fileData?.name?.endsWith('/documents/exam-tracker/data')||!fileData.fields)throw new Error('This is not the tracker backup file.');const obj=Object.fromEntries(Object.entries(fileData.fields).map(([k,v])=>[k,decodeFirestore(v)]));if(!Array.isArray(obj.students)||!Array.isArray(obj.submissions)||!Array.isArray(obj.classes))throw new Error('The backup is missing student, class, or result records.');return obj;}
function idPart(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,100);}
function readRows(){document.querySelectorAll('[data-row][data-field]').forEach(el=>{const row=state.scheduleRows[Number(el.dataset.row)];if(row)row[el.dataset.field]=el.value;});}

root.addEventListener('click',e=>{
  const b=e.target.closest('[data-action]');if(!b)return;
  const action=b.dataset.action;state.notice='';state.error='';
  if(action==='auth-mode'){state.authMode=b.dataset.mode;render();return;}
  if(action==='signout'){run(async()=>{await signOut(auth);state.user=null;state.profile=null;state.memberId=null;state.tab='today';});return;}
  if(action==='tab'){state.tab=b.dataset.tab;state.detail=null;state.paper='all';render();return;}
  if(action==='inspect-point'){state.selectedPoint={id:b.dataset.id,key:b.dataset.key};render();return;}
  if(action==='refresh'){run(refresh);return;}
  if(action==='check-verification'){run(async()=>{await reload(auth.currentUser);state.user=auth.currentUser;if(!state.user.emailVerified)throw new Error('Your email is not verified yet. Please open the link in the email, then try again.');await refresh();});return;}
  if(action==='resend-verification'){run(async()=>{await sendEmailVerification(auth.currentUser);state.notice='Verification email sent again.';});return;}
  if(action==='result'||action==='receipt'){state.detail={type:action,id:b.dataset.id};render();return;}
  if(action==='add-row'){readRows();state.scheduleRows.push(blankScheduleRow());render();return;}
  if(action==='remove-row'){readRows();state.scheduleRows.splice(Number(b.dataset.row),1);if(!state.scheduleRows.length)state.scheduleRows.push(blankScheduleRow());render();return;}
  if(action==='save-schedule'){readRows();run(saveSchedule);return;}
  if(action==='show-invite'){state.invitePreview=b.dataset.id;render();return;}
  if(action==='toggle-question'){run(async()=>{const key=b.dataset.key,explained=!state.questionStatus[key];await setDoc(doc(db,'questionStatus',encodeURIComponent(key)),{key,explained});state.questionStatus[key]=explained;state.notice=explained?'Question marked explained.':'Question returned to the class list.';});return;}
  if(action==='copy-invite'){run(async()=>{await navigator.clipboard.writeText(document.querySelector('#invite-link').value);state.notice='Invitation link copied.';});return;}
  if(action==='import-backup'){run(importLegacy);return;}
});
root.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.action==='inspect-point'){e.preventDefault();e.target.click();}});
root.addEventListener('change',e=>{const key=e.target.dataset.change;if(key){state[key]=e.target.value;if(key==='selectedClass')state.selectedExam='all';if(key==='selectedStudent'){state.paper='all';state.selectedPoint=null;}if(key==='paper'||key==='markView')state.selectedPoint=null;render();return;}if(e.target.id==='backup-file'){const file=e.target.files?.[0];if(!file)return;run(async()=>{const raw=JSON.parse(await file.text());state.importData=parseBackup(raw);state.notice=`Backup checked: ${state.importData.students.length} students and ${state.importData.submissions.length} results. No emails needed.`;});}});
root.addEventListener('submit',e=>{
  e.preventDefault();const form=e.target,values=new FormData(form);
  if(form.id==='auth-form'){run(async()=>{const email=emailKey(values.get('email')),password=String(values.get('password')||'');if(state.authMode==='reset'){await sendPasswordResetEmail(auth,email);state.notice='Password reset email sent if this account exists.';}else if(state.authMode==='signup'){const credential=await createUserWithEmailAndPassword(auth,email,password);await sendEmailVerification(credential.user);state.notice='Verification email sent. Open it before returning here.';}else await signInWithEmailAndPassword(auth,email,password);});return;}
  if(form.id==='claim-form'){run(async()=>{state.inviteUrl=String(values.get('invite')||'').trim();const url=new URL(state.inviteUrl),raw=new URLSearchParams(url.hash.slice(1)).get('invite')||'',split=raw.indexOf('.');if(url.origin!==location.origin||split<1)throw new Error('Use the full invitation link from your teacher.');state.invite={studentId:raw.slice(0,split),code:raw.slice(split+1)};const batch=writeBatch(db),profile=doc(db,'students',state.invite.studentId),member=doc(db,'members',state.user.uid);batch.update(profile,{authUid:state.user.uid,email:emailKey(state.user.email),claimProof:state.invite.code,inviteCode:deleteField()});batch.set(member,{studentId:state.invite.studentId,email:emailKey(state.user.email)});await batch.commit();history.replaceState(null,'',location.pathname+location.search);state.invite=null;state.inviteUrl='';await refresh();state.notice='Your account is connected to your earlier work.';});return;}
  if(form.id==='result-form'){run(async()=>{const id=form.dataset.id,a=state.assignments.find(x=>x.id===id),score=Number(values.get('score')),minutes=Number(values.get('minutes'));if(!a||!Number.isInteger(score)||score<0||score>a.total||!Number.isInteger(minutes)||minutes<1||minutes>1440)throw new Error('Enter a valid mark and actual minutes taken.');const questions=[...new Set(String(values.get('questions')||'').split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean))].slice(0,30);await setDoc(doc(db,'students',me(),'submissions',id),{assignmentId:id,classId:a.classId,score,minutes,questions,submittedAt:serverTimestamp()});state.detail=null;await refresh();state.tab='history';state.notice='Result saved. You can find it in My submissions.';});return;}
  if(form.id==='branding-form'){run(async()=>{const title=String(values.get('title')||'').trim(),subtitle=String(values.get('subtitle')||'').trim();if(!title||title.length>60||subtitle.length>80)throw new Error('Enter a title of up to 60 characters.');await setDoc(doc(db,'settings','app'),{title,subtitle});await refresh();state.notice='Website title saved.';});return;}
  if(form.id==='class-form'){run(async()=>{const name=String(values.get('name')||'').trim();if(!name)throw new Error('Enter a class name.');const ref=doc(collection(db,'classes'));await setDoc(ref,{name});await refresh();state.notice='Class added.';});return;}
  if(form.id==='student-form'){run(async()=>{const name=String(values.get('name')||'').trim(),classId=String(values.get('classId')||'');if(!name||!state.classes.some(c=>c.id===classId))throw new Error('Enter a name and class.');const ref=doc(collection(db,'students'));await setDoc(ref,{name,subject:String(values.get('subject')),classIds:[classId],inviteCode:newCode(),authUid:null,email:null});await refresh();state.invitePreview=ref.id;state.notice='Student added. Their private invitation is ready.';});return;}
  if(form.id==='membership-form'){run(async()=>{const studentId=String(values.get('studentId')||''),classIds=[...new Set(values.getAll('classIds').map(String))],subject=String(values.get('subject')||'');if(!state.students.some(s=>s.id===studentId)||!classIds.length||!classIds.every(id=>state.classes.some(c=>c.id===id))||!['olevel','as','a2','alevel','combined'].includes(subject))throw new Error('Choose a student, level and at least one class.');await setDoc(doc(db,'students',studentId),{classIds,subject},{merge:true});await refresh();state.membershipStudent=studentId;state.notice='Student level and classes saved.';});return;}
});
async function saveSchedule(){const rows=state.scheduleRows.map(x=>({...x,examLabel:String(x.examLabel||'').trim(),total:Number(x.total),paper:Number(x.paper),year:Number(x.year),variant:Number(x.variant)})),seen=new Set(),batch=writeBatch(db);for(const r of rows){if(!state.classes.some(c=>c.id===r.classId)||!r.examLabel||!['olevel','as','a2','alevel','combined'].includes(r.subject)||!['mar','jun','nov'].includes(r.session)||!Number.isInteger(r.total)||r.total<1||r.total>300||!Number.isInteger(r.paper)||r.paper<1||r.paper>9||!Number.isInteger(r.year)||r.year<2000||r.year>2100||!/^\d{4}-\d{2}-\d{2}$/.test(r.dueDate)||r.dueDate<today())throw new Error('Check every exam name, class, paper, total marks, and future due date.');const key=`${r.classId}|${r.examLabel.toLowerCase()}|${r.dueDate}`;if(seen.has(key)||state.assignments.some(a=>`${a.classId}|${a.examLabel.toLowerCase()}|${a.dueDate}`===key))throw new Error('The same exam is already scheduled for that class and date.');seen.add(key);const subject=r.subject,ref=doc(collection(db,'classes',r.classId,'assignments'));batch.set(ref,{examLabel:r.examLabel,examKey:`${subject}-${r.paper}-${r.year}-${r.session}-${r.variant}`,subject,paper:r.paper,year:r.year,session:r.session,variant:r.variant,total:r.total,dueDate:r.dueDate,createdAt:serverTimestamp()});}await batch.commit();state.scheduleRows=[blankScheduleRow()];await refresh();state.notice=`${rows.length} exam${rows.length===1?'':'s'} scheduled.`;}
async function importLegacy(){const old=state.importData;if(!old)throw new Error('Choose the backup file first.');if(state.students.length)throw new Error('Import is only available before students are added.');if(old.students.length+old.submissions.length+old.classes.length+1>490)throw new Error('This backup is too large for the one-step import.');const batch=writeBatch(db),ids=new Set(old.students.map(s=>String(s.id)));for(const c of old.classes)batch.set(doc(db,'classes',idPart(c.id)),{name:String(c.name||'Class')});for(const s of old.students){batch.set(doc(db,'students',idPart(s.id)),{name:String(s.name||'Student'),subject:String(s.subject||'olevel'),classIds:(s.classIds||[]).map(idPart),legacyId:String(s.id),inviteCode:newCode(),authUid:null,email:null});}for(const s of old.submissions){if(!ids.has(String(s.studentId)))continue;const id='legacy-'+idPart(s.id||crypto.randomUUID());batch.set(doc(db,'students',idPart(s.studentId),'submissions',id),{assignmentId:null,classId:null,examLabel:String(s.examLabel||''),examKey:String(s.examKey||''),subject:String(s.subject||''),paper:Number(s.paper)||0,year:Number(s.year)||0,session:String(s.session||''),variant:Number(s.variant)||0,score:Number(s.score)||0,total:Number(s.total)||1,minutes:Number(s.minutes)||0,questions:(s.difficultQuestions||[]).map(String),submittedAt:String(s.submittedAt||new Date().toISOString())});}batch.set(doc(db,'settings','app'),state.branding);await batch.commit();state.importData=null;await refresh();state.tab='roster';state.notice=`Imported ${old.students.length} students and ${old.submissions.length} earlier results. Old passcodes were left behind.`;}
onAuthStateChanged(auth,async user=>{state.user=user;state.teacher=user?.uid===TEACHER_UID;state.profile=null;state.error='';state.notice='';if(user&&(state.teacher||user.emailVerified)){try{await refresh();}catch(e){state.error=friendlyError(e);}}render();});
